### ISSUE TITLE
log_format_string is not defined

### ISSUE THREAD

**Issue by dlernstrom** [Digital-Sapphire/PyUpdater#1]
Hi.  Looking to use your library in a project.  pip installed cleanly.  Running on windows 7 / python 2.7 32 bit.

Within pyupdater/**init**.py, line 77 looks for a jms_utils.logger.log_format_string().  The setup installed jms-utils-1.0.2, which does not have a method log_format_string() inside of jms_utils.logger.

Any chance the version number dependency is wrong in the requirements file?  How can I help?

**Comment by dlernstrom** [comment]
Looking at the logger.py, I suspect you are really after jms_utils.logger.logging_formatter...

``` python
logging_formatter = logging.Formatter(u'[%(levelname)s] %(name)s '
                                      u'%(lineno)d: %(message)s')
```

**Comment by dlernstrom** [comment]
@JMSwag 
Disregard the issue.  Installed from the master branch and the problems went away.  The version out on pip is broken, btw.

Cheers,
David

**Comment by JMSwag** [comment]
@dlernstrom I'm hoping to get 2.0 pushed to pypi by Monday.
