### ISSUE TITLE
upload to Amazon

### ISSUE THREAD

**Issue by zockons12** [Digital-Sapphire/PyUpdater#101]
I am uploading a file to Amazon Storage though this does not seem to appear which is quite strange. This is for pyupdater. My only assumption is that for whatever reason it is either not loading the file correctly or not loading anything.

-Update.  I'm fairly certain that its not reading key and id properly which causes this issue... Now how to fix.

Hmm... As a side note, if I were to pay you a reasonable fee, would you be able to create simple exe that updates from amazon storage through patches?  Thanks.  I'm struggling a lot with the docs....

**Comment by JMSwag** [comment]
@Notagrumpycat Please provide the debug logs.

```
$ pyupdater collect-debug-info
```

**Comment by JMSwag** [comment]
No response from user
