### ISSUE TITLE
PyUpdater prints "{}" into console

### ISSUE THREAD

**Issue by 2press** [Digital-Sapphire/PyUpdater#105]
PyUpdater prints "{}" into console when checking for new versions.

**Comment by moscoquera** [comment]
that's not harmful, "{}" is a empty json maybe printed by the downloader.

**Comment by 2press** [comment]
Yes, I know that this is not harmful. But it is annoying anyway, if you have your program running with a console. It was introduced with the latest update.

**Comment by moscoquera** [comment]
even when log is disabled?

**Comment by eullerborges** [comment]
@moscoquera  I get this problem even when log is disabled.

**Comment by JMSwag** [comment]
Fixed in 3aafeed0ee121610b8bc05cb93cff18f422b03e1
