### ISSUE TITLE
If non-list provided to progress_hooks provide more informative error.

### ISSUE THREAD

**Issue by flutefreak7** [Digital-Sapphire/PyUpdater#111]
I think a more informative traceback should be provided if a progress_hook is used and the user forgot to place their hooks into a list.

Here's where the assert change was implemented:
https://github.com/JMSwag/PyUpdater/commit/8d1b1a0b0f4928c672c1fface281df8098328b82#diff-850b8236548c5fdf368dc6394b417872R126

Perhaps...

    if not isinstance(progress_hooks, list):
        raise SyntaxError('progress_hooks must be provided as a list.')

It would also be more "pythonic" to just check if it's an Iterable or a Sequence or whatever using collections.abc, but it's probably unlikely someone would store their hooks in a non-list, but list-like container.

**Comment by JMSwag** [comment]
Fixed in 84ff0f80481f2c24994626c9ac549652cb3138ea
