### ISSUE TITLE
Add support for cython

### ISSUE THREAD

**Issue by wolfamongus2** [Digital-Sapphire/PyUpdater#112]
SUMMARY:

You cannot put pyupdater in a cython/pyx file.  This causes security concerns namely, the fact you have to put your credentials in a .py file.

Possible workaround?

Create a cythoned pyx file, and put your credentials in there.  This is questionable, as you can view it in log and also without suppressed prints.  I also believe pyupdater has some strange print feature in downloader.py which prints auth credentials.

That being said, someone would have to remove those lines and rebuild the python script which is a real pain for them to do if they wanted your script.

Might be worth an investigation on how to cythonise pyupdater part.  Cythonising credentials atm, I am unsure if this is secure

**Comment by JMSwag** [comment]
Hey @wolfamongus2, a PR providing this functionality is welcome.

**Comment by JMSwag** [comment]
@wolfamongus2 I've been able to successfully cythonize pyupdater.client.Client. Please reopen this issue if still having issues.
