### ISSUE TITLE
Moving initialized repo

### ISSUE THREAD

**Issue by Devligue** [Digital-Sapphire/PyUpdater#115]
I have problem with moving initialized repo. Well in fact it is not a problem since I can solve it manually in few ways but I think PyUpdater should be able to manage it somehow a bit better.

##### Description:
I want to develop application for both Windows and Linux. I can't do it only on Windows. I need both of the systems. This means that I will need the same project in two different places. 

##### Possibility 1:
I can check out all my source code on both development machines and then initialize the repo exactly the same way on both and import the same kays. It will work but not quiet. You see the version_meta that is present in `.pyupdater/config.pyu` is responsible for the content of the `versions.gz` file. So when I upload new binaries to update server from Linux the `version.gz` from Linux repo will override existing ones and since in Linux `versions.gz` there is no information about Windows versions, my Windows binaries will not be able to update. And also the other way round.

##### Possibility 2:
I can check out all my source code on both dev machines **including** the `.pyupdater/config.pyu` file. To make it work I would then need to manually change the `config_dir`, `filename` and `DATA_DIR` in `.pyupdater/config.pyu` so that the paths match my project. But then again I will have to correct this every time that the other machine deployed binaries. I thought that if I run `pyupdater settings` with no arguments it will automatically update itself, but no. It printed the right paths to console, but did not changed them in the `config.pyu`.

##### Possibility 3:
I can build on seperate machines from identically initialized repos, but then copy all files from `pyu-data/new` direstory to one, and then sign and deploy them together. Works but it is not very handy, isn't it?

##### Possibility 4:
Finally I can use different repos for different platforms with different update url. But that does not talk to me very well.

What is the preferred procedure for this?

**Comment by JMSwag** [comment]
@Devligue Most of my apps are Mac & Windows but the same should apply.

Essentially I --process and --sign my updates on my main system (mac) once the updates are built on all the other platforms. I keep the repository in sync with resilio-sync but any syncing software should work. Hope this helps.

**Comment by Devligue** [comment]
@JMSwag I guess that this is the best solution for now. But there is another thing. What if I need to change my main development system and move it to other PC (with same OS, for simplification)? I can not simply init new pyupdater repo on different pc, even if I provide the same keypack and config settings, the same plugin settings, the same source code and spec file and everything. Because event then my version_meta will be missing from config.pyu. This is where I thought of:

> Possibility 2:
> I can check out all my source code on both dev machines including the .pyupdater/config.pyu file. To make it work I would then need to manually change the config_dir, filename and DATA_DIR in .pyupdater/config.pyu so that the paths match my project. But then again I will have to correct this every time that the other machine deployed binaries. I thought that if I run pyupdater settings with no arguments it will automatically update itself, but no. It printed the right paths to console, but did not changed them in the config.pyu.

So here I ask, **is it a correct behavior, that when I copy entire `.pyupdater` directory to other machine, and then call `pyupdater settings`, it tells me that it updates the paths and saves them to `config.pyu` even though it does not?** And if yes, can it in future be changed to **actually update the paths**?

I hope that I'm making sense 😃

**Comment by JMSwag** [comment]
@Devligue I'm a little confused.
