### ISSUE TITLE
[ERROR] [Errno 2] No such file or directory: 'nix64'

### ISSUE THREAD

**Issue by JPFrancoia** [Digital-Sapphire/PyUpdater#12]
Hi,

Your tools seems great. I'm trying it at the moment.
I started with a simple script, test.py:

``` python
#!/usr/bin/python
# coding: utf-8

import sys
import os

print("Testing")

if __name__ == '__main__':
    pass
```

Nothing complicated here. I then used `pyinstaller test.py` to get the spec file, test.spec (I want to try pyupdater with a spec file because for I want to do next, I'll need a spec file).

Then I ran `pyupdater init`, answered the questions, and ran `pyupdater build --app-version 1.0 test.spec`. And here is what I got:

```
[INFO] PyInstaller: 3.2
[INFO] Python: 3.5.2
[INFO] Platform: Linux-4.4.19-1-MANJARO-x86_64-with-glibc2.3.4
[INFO] UPX is available.
[INFO] Extending PYTHONPATH with paths
['/home/djipey/informatique/python/updater',
 '/home/djipey/informatique/python/updater']
[INFO] checking Analysis
[INFO] Building Analysis because out00-Analysis.toc is non existent
[INFO] Initializing module dependency graph...
[INFO] Initializing module graph hooks...
[INFO] Analyzing base_library.zip ...
[INFO] running Analysis out00-Analysis.toc
[INFO] Caching module hooks...
[INFO] Analyzing test.py
[INFO] Loading module hooks...
[INFO] Loading module hook "hook-encodings.py"...
[INFO] Loading module hook "hook-pydoc.py"...
[INFO] Loading module hook "hook-xml.py"...
[INFO] Looking for ctypes DLLs
[INFO] Analyzing run-time hooks ...
[INFO] Looking for dynamic libraries
[INFO] Looking for eggs
[INFO] Using Python library /usr/lib/libpython3.5m.so.1.0
[INFO] Warnings written to /home/djipey/informatique/python/updater/.pyupdater/work/test/warntest.txt
[INFO] checking PYZ
[INFO] Building PYZ because out00-PYZ.toc is non existent
[INFO] Building PYZ (ZlibArchive) /home/djipey/informatique/python/updater/.pyupdater/work/test/out00-PYZ.pyz
[INFO] checking PKG
[INFO] Building PKG because out00-PKG.toc is non existent
[INFO] Building PKG (CArchive) out00-PKG.pkg
[INFO] Bootloader /usr/lib/python3.5/site-packages/PyInstaller/bootloader/Linux-64bit/run
[INFO] checking EXE
[INFO] Building EXE because out00-EXE.toc is non existent
[INFO] Building EXE from out00-EXE.toc
[INFO] Appending archive to ELF section in EXE /home/djipey/informatique/python/updater/.pyupdater/work/test/test
[INFO] checking COLLECT
[INFO] Building COLLECT because out00-COLLECT.toc is non existent
[INFO] Removing dir /home/djipey/informatique/python/updater/pyu-data/new/test
[INFO] Building COLLECT out00-COLLECT.toc
[ERROR] [Errno 2] No such file or directory: 'nix64'
```

Building directly from test.py completed, but not from test.spec. What should I do to solve this ?

**Comment by JMSwag** [comment]
@JPFrancoia please reply with the contents of your spec file.

**Comment by JMSwag** [comment]
@JPFrancoia I was able to reproduce your issue. I used the steps below to successfully build the app. Let me know if you're still having issues.

```
$ pyupdater make-spec --app-version 1.0 test.py
$ pyupdater build --app-version 1.0 nix64.spec
```

Note: The next release will remove the need to specify --app-version when building a spec file. This is being tracked here #13

**Comment by JPFrancoia** [comment]
It worked like a charm, the build completed, thanks !

Ok now I have some questions. With the steps above, we basically created the spec file with pyupdater. I have a _real_ project (not a test), with a rather complicated spec file. What will I need to modify to make it usable by pyupdater ?

**Comment by JMSwag** [comment]
You'll need a separate spec file for each platform your targeting. The spec file should build single file output. The name field in the spec file should be one of mac, win, nix, nix64.

**Comment by JPFrancoia** [comment]
Sorry, stupid question. It's actually more simple to create the spec file with pyupdater than modifying the spec file created with pyinstaller.

However, I don't like the idea of a platform-dependant spec file. I will create a condition to choose the right name, depending on the platform I am building on. I will therefore have only one spec file to maintain.

Thanks for your help !

Can I suggest a slight update of the example of the doc (User Guide > Commands > build):

From

```
# Build from python script
$ pyupdater build -F --app-version 1.0 app.py
# Build from spec file
$ pyupdater build --app-version 1.2 app.spec
```

to 

```
# Build from python script
$ pyupdater build -F --app-version 1.0 app.py
# Build from spec file (see Usage on how to create spec files)
$ pyupdater build --app-version 1.2 app.spec
```

So that future users won't (like me) wonder why their spec file isn't working ?

**Comment by JMSwag** [comment]
No problem at all. I'll get those docs updated right away.

Suggestions are always welcome :)
