### ISSUE TITLE
Fix arm support

### ISSUE THREAD

**Issue by JMSwag** [Digital-Sapphire/PyUpdater#120]
See https://github.com/JMSwag/PyUpdater/commit/cd72ca9160cd245597de31ded0659ec1efc490e6

**Comment by riq-dfaubion** [comment]
This is what I'm using: https://github.com/JMSwag/PyUpdater/pull/123

**Comment by JMSwag** [comment]
Fixed in 3dbaf2ded46ef8d3d7c04b67849fee89fb8f2645
