### ISSUE TITLE
Keypack wont generate

### ISSUE THREAD

**Issue by LucCole** [Digital-Sapphire/PyUpdater#127]
Does anyone know what the problem is? I cant seem to get the keypack to generate. I tried to create the keys with my computer offline but that didn't seem to help any.

```
225 INFO: PyUpdater 2.5.3
[INFO] PyUpdater 2.5.3
229 ERROR: You can not create off-line keys on your dev machine
[ERROR] You can not create off-line keys on your dev machine
```

**Comment by p4k1tz** [comment]
I second this, I am unable to create keys at all. The documentation asks to create the keys first, but check_repo_ex expects it to be initialized. Even if i initialize a directory, I am getting the following error.

```
C:\pyupdater>py36 -m pyupdater keys --create
[INFO] PyUpdater 2.5.3
[ERROR] You can not create off-line keys on your dev machine
```

I have overridden this check to try an alleviate the issue but get the same. 

```
C:\>py36 -m pyupdater keys --create
[INFO] PyUpdater 2.5.3
[ERROR] Not a PyUpdater repo: You must initialize your repository first
Please enter app name - No Default Available
--> thisapp
You entered thisapp, is this correct?
[N/y]?y
[ERROR]
[ERROR] Failed to create keypair; please report this issue on https://github.com/JMSwag/PyUpdater/issues
[ERROR] Failed to create keypack
```

Any insight would be so greatly appreciated!

**Comment by JMSwag** [comment]
You have to create the keys in a directory other than the root of your repository. Please reopen if you are still having trouble.

**Comment by Zageron** [comment]
`erane@ADAM F:\git\demos\pyupdater-wx-demo
# pyupdater keys -c
[INFO] PyUpdater 0+unknown
[ERROR] You can not create off-line keys on your dev machine`

`Python 3.7.2`

This is immediately after initializing my pyupdater according to the demo.

Thanks,
