### ISSUE TITLE
too large about 100M with only import pyupdater.client.Client

### ISSUE THREAD

**Issue by njxz** [Digital-Sapphire/PyUpdater#129]
python == 3.6
pyinstaller ==3.3
pyupdater == 2.5.3

run.py :
 `from pyupdater.client import Client`

when  i package the python file,
`pyupdater build  --app-version 1.0.0 run.py -Fw`
it's so large than i image 
it's 120MB zip file
How can i decrease the size of the package file

**Comment by JMSwag** [comment]
@njxz I'm not seeing the same. Maybe something else being imported. Whats the size when compiled without importing the client? Please reopen if you still find the issue being PyUpdater.
