### ISSUE TITLE
Post-Update Routine

### ISSUE THREAD

**Issue by witalij-s** [Digital-Sapphire/PyUpdater#133]
Hi all,

i am looking for a method to do routines after updating and untaring a file. Like copying .desktop files or copying shell scripts to a certain location. What do you think would be a proper way to do this? And where in the code would it fit?

Best,
Witalij

**Comment by JMSwag** [comment]
@witalij-s This is out of scope for PyUpdater. You may want to ship the generated archive by way of an installer which completes the steps mentioned.
