### ISSUE TITLE
Support For Python 3.6

### ISSUE THREAD

**Issue by p4k1tz** [Digital-Sapphire/PyUpdater#138]
Hello, I have noticed that the module is able to be installed through pip on Python 3.6, but I cannot generate keys. I have setup a Python 2.7 environment and successfully created keys and initialized my app.

Is Python 3.6 supposed to work and if not, when can we expect to see a release compatible?

**Comment by JMSwag** [comment]
@thagh05t Hey! Python 3.6 is supported. What errors are you getting? Which platform are you using?

**Comment by p4k1tz** [comment]
I am on Windows 10 x64 at the moment of testing and am getting the below output.

```
Z:\username\Documents\keyspyupdate>py36 -m pyupdater keys --create
[INFO] PyUpdater 2.5.3
[ERROR] Not a PyUpdater repo: You must initialize your repository first
Please enter app name - No Default Available
--> testApp
You entered testApp, is this correct?
[N/y]?y
[ERROR]
[ERROR] Failed to create keypair; please report this issue on https://github.com/JMSwag/PyUpdater/issues
[ERROR] Failed to create keypack
```

I can run the init command just fine, but cannot create keys in the initialized dir (by design looking over the source) Any other info needed, please dont hesitate to ask, I would love to get this working. I will create some video tutorials with some gotchas as gratitude. 

I would also like to note that I couldnt get pyinstaller working on Python 3.6 either. gave me an index out of range error, which looks like it is being tracked, but I didnt find the issue closed.

**Comment by p4k1tz** [comment]
Is there a specific release known to be working for 3.6 by chance?

**Comment by JMSwag** [comment]
There is a known issue with 64bit Python on windows. If possible try 32bit Python. 

The issue is actually with the python-ed25519 library being used.

**Comment by p4k1tz** [comment]
Sure thing, give me an hour and I'll confirm.

**Comment by JMSwag** [comment]
Cool! I’ll be online tonight.

**Comment by p4k1tz** [comment]
Looking good, so far! I was able to create keys and init an app. I am going to do a full build and test S3, but I think this issue can be closed.

**Comment by JMSwag** [comment]
@thagh05t Sounds good!

**Comment by p4k1tz** [comment]
Alright, I have tested a lot of the functionality with Python 3.6.6 x86_64 on Win10 with huge success. Nice job.

**Comment by generalectric** [comment]
for me the solution is to run pyupdater in winbash running ubuntu in my repo home folder to sign the packages
