### ISSUE TITLE
`codesign` support on MacOS

### ISSUE THREAD

**Issue by Fizzadar** [Digital-Sapphire/PyUpdater#139]
I'm having issues signing the app bundles output by `pyupdater` that work with `pyinstaller`. My plan was to untar -> sign -> re-tar the bundles in `pyu-data/new` before running process/sign.

```
pyu-data/Kanmail.app: bundle format unrecognized, invalid, or unsuitable
In subcomponent: [...]/Kanmail.app/Contents/MacOS/include/python3.6m
```

I did some digging at the bundles output by installer vs updater and discovered how:

+ the working `pyinstaller` bundle contains symlinks from `MacOS/lib`/etc to `../Resources/...`
+ the `pyupdater` build has copies of the files in both locations - which looks odd?

Happens for all the files/folders inside `Resources` that are also duplicated in `MacOS`. I can't figure out why this would be different though!

Removing the duplicates and creating symlinks fixes the issue as a workaround.

**Comment by JMSwag** [comment]
@Fizzadar in my experience, with pyinstaller, the only item included in the MacOS sub directory is the executable itself. Did you create your spec file with pyinstaller or pyupdater?

**Comment by Fizzadar** [comment]
@JMSwag apologies for the delay - yes I believe I generated the original using pyupdater. It's since become a template (https://github.com/Fizzadar/Kanmail/blob/develop/make/spec_mac.j2.py).

**Comment by JMSwag** [comment]
Hey @Fizzadar, no worries! I think our issue may be [here](https://github.com/JMSwag/PyUpdater/blob/master/pyupdater/utils/__init__.py#L281). Please try my issue-139 branch.

**Comment by Fizzadar** [comment]
@JMSwag that's it - works a charm on the `issue-139` branch!

**Comment by JMSwag** [comment]
Cool beans! I'll get it merged into master later today.
