### ISSUE TITLE
Restarting / updating the application on Mac does nothing

### ISSUE THREAD

**Issue by JessicaTegner** [Digital-Sapphire/PyUpdater#141]
Hi.
Using the app_update.extract_restart() method on mac does nothing.
There's no traceback, the .app file doesn't get replaced but the application in question gets shutdown successfully.
I've tried with both the latest version from pypi and from the GitHub repository, yelling the same result.

Here's my setup:
* Python 3.7
* mac os mojave

The same code works on my windows setup, with the same code / project and python version, both with the latest PyUpdater version from pypi and from GitHub.
I really don't know what's wrong.

**Comment by JMSwag** [comment]
@NicklasMCHD Hey, py37 hasn't been tested so not supported just yet. Try with py36. If still having issues please reopen this issue.

**Comment by JessicaTegner** [comment]
I've tested the code on Python 3.6, both the pypi version and GitHub master, with the same results @JMSwag

**Comment by JMSwag** [comment]
@NicklasMCHD Can you provide a minimal example app? Also, do you have any logs you can post? I've been using py36 on windows & mac without issue.

**Comment by JessicaTegner** [comment]
I have followed the wx demo application example from http://pyupdater-wx-demo.readthedocs.io/en/latest/overview.html
and that works fine for me on Windows only. Am I missing anything does my app need to be installed (via a pkg) or can I just drop it in the Applications folder from something like a .dmg?
I have no log output (since my application doesn't yel any errors).
The only difference is, that on windows it updates and starts again, while on mac nothing happens.
@JMSwag

**Comment by JMSwag** [comment]
I've had success with just dropping the app in the applications folder and by way of .dmg. I use pyqt5 as my GUI framework though. 

When trying the wx pyupdater demo project, I'm seeing the error shown below.
```
$ PYUPDATER_FILESERVER_DIR=<path to update directory> ./PyUpdaterWxDemo.app/Contents/MacOS/PyUpdaterWxDemo

127.0.0.1 - - [12/Jan/2019 12:59:33] "POST /shutdown HTTP/1.1" 200 -
 * Serving Flask app "wxupdatedemo.fileserver" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "run.py", line 175, in <module>
  File "run.py", line 156, in Run
  File "run.py", line 95, in StartFileServer
  File "wxupdatedemo/fileserver.py", line 73, in WaitForFileServerToStart
  File "requests/api.py", line 60, in get
  File "requests/api.py", line 49, in request
  File "requests/sessions.py", line 443, in request
  File "requests/sessions.py", line 374, in prepare_request
  File "requests/models.py", line 304, in prepare
  File "requests/models.py", line 365, in prepare_url
LookupError: unknown encoding: idna
[63099] Failed to execute script run
```
You will more than likely find success by signing up for a free aws account and using [s3](https://github.com/JMSwag/PyUpdater-S3-Plugin) or using [scp](https://github.com/JMSwag/PyUpdater-SCP-Plugin) with an existing server with a sample project.

**Comment by JessicaTegner** [comment]
@JMSwag I'm using the scp plugin, uploading over ssh to my own server.

**Comment by JMSwag** [comment]
Sorry, I should have been more clear. Please use a sample project of your own creation instead of the wx demo.
