### ISSUE TITLE
Keypack wont generate.

### ISSUE THREAD

**Issue by Zageron** [Digital-Sapphire/PyUpdater#144]
@JMSwag

```shell
pyupdater keys -c
[INFO] PyUpdater 0+unknown
[ERROR] You can not create off-line keys on your dev machine
```

`Python 3.7.2`

This is immediately after initializing my pyupdater according to the demo.

Thanks,

#127 Similar to this, but it didn't help me.

**Comment by JMSwag** [comment]
@Zageron The [docs](https://www.pyupdater.org/usage-cli/) advise to create your keypack on an offline computer. If this is not feasible then you'll need to create the keypack in a directory other than your repository. The following files, [utils/__init__.py](https://github.com/JMSwag/PyUpdater/blob/052476e394fe4667417b4bb1652c61be39d391df/pyupdater/utils/__init__.py#L193-L199) & [commands.py](https://github.com/JMSwag/PyUpdater/blob/052476e394fe4667417b4bb1652c61be39d391df/pyupdater/cli/commands.py#L221-L223) show that this error is thrown when attempting to create a keypack when inside your repository after pyupdater has been initialized which is not correct.

If you run the "ls -a" command in the same directory in which you see the error provided, the ".pyupdater" folder will be present which causes the error to be thrown.

**Comment by Zageron** [comment]
I looked through the code, and I'll note two things.
```
$ pyupdater keys -c
[INFO] PyUpdater 0+unknown
[ERROR] Not a PyUpdater repo: You must initialize your repository first
Please enter app name - No Default Available
--> 
```

@JMSwag Your suggestion worked, but it threw two errors which made me think that I was initializing my repository with the command. Anyway, thank you for the help!

**Comment by JMSwag** [comment]
@Zageron NP!
