### ISSUE TITLE
CI Test failures - PIP issue

### ISSUE THREAD

**Issue by JMSwag** [Digital-Sapphire/PyUpdater#145]
See https://github.com/pypa/pip/issues/6163

Instead of trying to pin an older version of pip, I think we should wait for the fix which should be out by early next week. Thoughts?

**Comment by 2press** [comment]
I agree. Nonetheless, maybe we should add a `pip != 19.0.1` or at least a warning if one tries to install with this version of pip.

**Comment by 2press** [comment]
Pip 19.0.2 is now released.

**Comment by JMSwag** [comment]
@2press Thanks! Tests are looking good.
