### ISSUE TITLE
Trying to get Eel running with PyUpdater

### ISSUE THREAD

**Issue by AxelRHD** [Digital-Sapphire/PyUpdater#146]
I am trying to build an electron-like application with Eel in Python. Unfortunately Eel uses it's own "version" of packing it's application with PyInstaller. I am not that pro with Python (yet) and so I can't put together the lose ends of PyUpdater (PyInstaller) and the Eel lib. Is there a way to get that done? Maybe prebuilt the app with the script of Eel, but with the update-functionality of PyUpdater? It would be a great deal having an electron-like Python app with the ability of self-updating.

**Comment by JMSwag** [comment]
@AxelRHD PyUpdater was written to work with pyinstaller directly.
