### ISSUE TITLE
Pyupdater.org domain seems to be unregistered

### ISSUE THREAD

**Issue by bobgroneman** [Digital-Sapphire/PyUpdater#148]
All the doco links point to pyupdater.org, which appears to have it's domain registration expired (and hence the documentation links do not work)

**Comment by douglasmccormickjr** [comment]
I'm seeing this as well

**Comment by ArkFreestyle** [comment]
Me too! Can't find documentation :(

**Comment by king1037** [comment]
what happen to pyupdater?Gave up?

**Comment by JMSwag** [comment]
I’ll get this fixed in the next day or so. In the mean time, you guys can install mkdocs then run “mkdocs build --clean”.

**Comment by douglasmccormickjr** [comment]
@king1037 -- @JMSwag has too much swag to give up...I love this library/module/package...It's really really cool-- thank you so much.

**Comment by JMSwag** [comment]
Resolved. @bobgroneman, Thanks for the heads up!
