### ISSUE TITLE
Use PyUpdater to auto update a pypi lib

### ISSUE THREAD

**Issue by shaicantor** [Digital-Sapphire/PyUpdater#15]
Hi there,

I stumbled upon your great package.
I have a pytest plugin that I want to auto update upon test run if needed.
I couldn't figure out how I do that with pyupdater, **even after reading the documentation**.
1. Can I do it with pyupdater?
2. Do you guys support downloading files from pypi?
3. If so, can you please give me some pointers on how to start?

Thanks

**Comment by JMSwag** [comment]
PyUpdater is used for frozen python scripts.

For your case you can include something similar to the below in a make or batch file.

```
pip install --upgrade plugin-name
tox
```
