### ISSUE TITLE
[WIP] One dir support

### ISSUE THREAD

**Issue by JMSwag** [Digital-Sapphire/PyUpdater#16]
To add support for pyinstaller onedir, the following functions & methods need to be updated.
- [ ] pyupdater.builder.Builder
  - ._make_spec -> remove addition of "-F"
- [ ] pyupdater.utils
  - make_archive -> Make directory compatible
- [ ] pyupdater.utils.Restarter
  - ._win_overwrite -> Make directory compatible
  - ._win_overwrite_restart -> make directory compatible
- [ ] pyupdater.client.updates.AppUpdate
  - ._overwrite -> Make directory compatible

**Comment by dermyrddin** [comment]
Hi, do you have any milestone for this?

**Comment by JMSwag** [comment]
Not at the moment.

## 

JMSwag
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by JMSwag** [comment]
@merlineus I've added a milestone. v3.0

**Comment by ben-willmore** [comment]
This patch makes updating work for my onedir app on non-Windows platforms. It assumes that the .tar.gz contains only one item at the top level (a file for one_file, a dir for one_dir), and that, for one_dir, the binary is one level deep inside the directory. I don't know how general those assumptions are.

 https://gist.github.com/beniamino38/6fcb742b620085de75c22de340580f96

**Comment by JMSwag** [comment]
@beniamino38 Thanks for the patch! It's a great starting point for the complete implementation.

**Comment by ben-willmore** [comment]
In case anyone uses the patch, sys.executable works better than sys.argv[0]
