### ISSUE TITLE
[WinError 3] The system cannot find the path specified: 'win'

### ISSUE THREAD

**Issue by webpolis** [Digital-Sapphire/PyUpdater#167]
Hi

I'm trying to build a package on Windows 8.1 using **pyupdater** but the following happens after the Analysis phase of the pyinstaller spec file. I'm running the command:

` pyupdater build --onefile --app-version 0.1.0 main.win.spec` and the spec file looks as follows:

```
# -*- mode: python -*-
from kivy.utils import platform
from os.path import join, exists
import kivy
import os

NAME = 'test'
CURDIR = os.path.abspath(SPECPATH)

block_cipher = None

if platform == 'win':
    from kivy.deps import sdl2#, glew, gstreamer
else:
    glew = sdl2 = None

a = Analysis(
    ['./src/main.py', './dist/obf/main.py'],
    pathex=[CURDIR],
    binaries=[
        ('./dev/smf.dll', '.')
    ],
    datas=[
        ('./dev/smf.dll', '.'),
        ('./dist/obf/*.lic', '.'),
        ('./dist/obf/*.key', '.'),
        ('./dist/obf/_pytransform.*', '.'),
        ('./dist/obf/pytransform.py', '.'),
        ('./src/assets', 'assets'),
        ('./src/ui/views', 'ui/views'),
        ('./src/product/assets/cert.pem', 'product/assets'),
        ('./src/product/assets/license.key', 'product/assets'),
    ],
    hiddenimports=['kivy.garden', 'win32timezone'],
    hookspath=['/Program Files/Python37/Lib/site-packages/pyupdater/hooks/'],
    runtime_hooks=[],
    excludes=['numpy'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False
)

for ii in range(len(a.scripts)):
    if a.scripts[ii][1].startswith(a.pathex[0]):
        print(a.scripts[ii])
        a.scripts[ii] = a.scripts[ii][0], a.scripts[ii][1].replace(a.pathex[0], os.path.abspath('dist/obf')), a.scripts[ii][2]
        print(a.scripts[ii])

print('-------------------------------------------------------------------------------')

for i in range(len(a.pure)):
    if a.pure[i][1].startswith(a.pathex[0]):
        print(a.pure[i])
        a.pure[i] = a.pure[i][0], a.pure[i][1].replace(a.pathex[0], os.path.abspath('dist/obf')), a.pure[i][2]
        print(a.pure[i])

pyz = PYZ(
    a.pure,
    a.zipped_data,
    cipher=block_cipher
)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    name=NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    runtime_tmpdir=None,
    console=False
)

coll = COLLECT(
    exe,
    a.zipfiles,
    *([Tree(p) for p in (sdl2.dep_bins)] if sdl2 else []),
    strip=False,
    upx=True,
    name=NAME
)

```

This works perfectly fine using **pyinstaller** directly, so there's some issue related to PyUpdater I'm not able to trace back since it's completely ignoring the `--log-level DEBUG`  flag.

Please, I appreciate any help.

**Comment by JMSwag** [comment]
@webpolis PyUpdater does not work with spec files generated by pyinstaller. You'll need to create a spec file, see [make spec](https://www.pyupdater.org/usage-cli/#step-6-make-spec),  with pyupdater then update it to your needs. This should be made clearer in the docs & added to the [danger zone](https://www.pyupdater.org/danger-zone/#spec-file) section. I'll leave this issue open until I make those additions.

**Comment by webpolis** [comment]
@JMSwag what's the crucial difference between both spec files that would cause PyUpdater to fail? Indeed, I have generated the spec via PyUpdater (which doesn't show any relevant difference with PyInstaller's one) and still fails. In fact, there's no real difference except the custom `hiddenimports` and other parameters that are required for this project:

PyUpdater:

```
# -*- mode: python -*-
block_cipher = None

a = Analysis(['/home/nico/Music/arpado/src/main.py'],
             pathex=['/home/nico/Music/arpado', '/home/nico/Music/arpado'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=['/home/nico/miniconda2/envs/py36/lib/python3.6/site-packages/pyupdater/hooks'],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='nix64',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=False )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='nix64')
```

Mine (which was originally generated with PyUpdater but adapted to suit project's requirements):

```
# -*- mode: python -*-
block_cipher = None

a = Analysis(
    ['./src/main.py', './dist/obf/main.py'],
    pathex=[CURDIR],
    binaries=[],
    datas=[
        ('./dist/obf/*.lic', '.'), 
        ('./dist/obf/*.key', '.'), 
        ('./dist/obf/_pytransform.*', '.'), 
        ('./dist/obf/pytransform.py', '.'),
        ('./src/assets', 'assets'),
        ('./src/ui/views', 'ui/views'),
        ('./src/product/assets/cert.pem', 'product/assets'),
        ('./src/product/assets/license.key', 'product/assets'),
    ],
    hiddenimports=['kivy.garden'],
    hookspath=['/home/nico/miniconda2/envs/py36/lib/python3.6/site-packages/pyupdater/hooks'],
    runtime_hooks=[],
    excludes=['numpy'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False
)

pyz = PYZ(
    a.pure,
    a.zipped_data,
    cipher=block_cipher
)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    name=NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    runtime_tmpdir=None,
    console=False
)

coll = COLLECT(
    exe,
    a.zipfiles,
    *([Tree(p) for p in (sdl2.dep_bins)] if sdl2 else []),
    strip=False,
    upx=True,
    name=NAME
)
```

Can you spot the difference that could cause such an error? Like said, this builds perfectly using PyInstaller directly.

Thanks

**Comment by JMSwag** [comment]
@webpolis PyUpdater changes the name argument in the spec file. See [builder.py](https://github.com/JMSwag/PyUpdater/blob/master/pyupdater/builder.py#L139-L165). The name attribute looks to have been changed from what was generated by PyUpdater. Again see [builder.py](https://github.com/JMSwag/PyUpdater/blob/master/pyupdater/builder.py#L93)

I'm thinking the steps to success would be as follows.

1. Generate a fresh spec file with PyUpdater
2. Take all of your additions from the spec file working with pyinstaller, except for the name argument, and put them in the PyUpdater generated spec file.
3. Attempt a build with the updated spec file that was originally generated from PyUpdater.

Hope this helps!

**Comment by JMSwag** [comment]
No response from reporter

**Comment by RussNelson** [comment]
I'm looking at builder.py in build() where it says `temp_name = get_system()` and then ignores it if you've specified a .spec file in `app_info["type"]` but then goes on to call `self._archive(temp_name)`. This is in pyupdater 4.0. The error is getting thrown from _archive because 'win' (which is what `get_system()` returns on Windows, for some reason) doesn't exist because the temp_file spec hasn't been created.
