### ISSUE TITLE
OneFile-mode produces invalid 1KB .zip-File

### ISSUE THREAD

**Issue by Jazzman82** [Digital-Sapphire/PyUpdater#168]
We are using pyupdater v2.5.3 on windows to create windows executable.

When calling pyudater with -F or --onefile parameter, it creates an invalid .zip which has only a size of 22 bytes size.
`pyupdater build --onefile --app-version 1.0.0 app.py`

Leaving the parameter out, it works all as expected. We would really want to use one-file mode because the available space on the target machines is pretty low so any MB saved helps here.

When called with -k parameter, we see a win.exe-File in the pyu-data\new directory which in fact is executable and working as expected so it seems there is some error in the steps following the pyinstaller single-file build.

**Comment by Jazzman82** [comment]
For deeper investigation, here is the output of the following command:
`C:\repos\Client>pyupdater build --name  MachineSoftware --onefile --app-version 1.0.0 MachineSC.py -k
1249 INFO: PyUpdater 2.5.3
[INFO] PyUpdater 2.5.3
1264 DEBUG: Config Dir: C:\repos\Client\.pyupdater
1264 DEBUG: Config DB: C:\repos\Client\.pyupdater\config.pyu
1266 DEBUG: Building from python source file: MachineSC.py
1267 DEBUG: Source file abs path: C:\repos\Client\MachineSC.py
1301 DEBUG: Creating directory: C:\repos\Client\.pyupdater\work
1304 DEBUG: App Info: {u'type': u'script', u'name': 'C:\\repos\\Client\\MachineSC.py'}
1305 DEBUG: Hook directory: c:\el\tools\python\python27\lib\site-packages\pyupdater\hooks
1305 DEBUG: Make spec cmd: --onefile --name=win --specpath=C:\repos\Client\.pyupdater\spec --additional-hooks-dir=c:\el\tools\python\python27\lib\site-packages\pyupdater\hooks C:\repos\Client\MachineSC.py
1313 INFO: wrote C:\repos\Client\.pyupdater\spec\win.spec
[INFO] wrote C:\repos\Client\.pyupdater\spec\win.spec
1314 DEBUG: Version str: 1.0.0
1315 DEBUG: Build cmd: --distpath=C:\repos\Client\pyu-data\new --workpath=C:\repos\Client\.pyupdater\work -y C:\repos\Client\.pyupdater\spec\win.spec
1723 INFO: PyInstaller: 3.4
[INFO] PyInstaller: 3.4
1723 INFO: Python: 2.7.9
[INFO] Python: 2.7.9
1724 INFO: Platform: Windows-8-6.2.9200
[INFO] Platform: Windows-8-6.2.9200
1728 INFO: UPX is not available.
[INFO] UPX is not available.
1731 INFO: Extending PYTHONPATH with paths
['C:\\repos', 'C:\\repos\\Client', u'C:\\repos\\Client\\.pyupdater\\spec']
[INFO] Extending PYTHONPATH with paths
['C:\\repos', 'C:\\repos\\Client', u'C:\\repos\\Client\\.pyupdater\\spec']
1733 INFO: checking Analysis
[INFO] checking Analysis
1Traceback (most recent call last):
  File "c:\el\tools\python\python27\lib\logging\__init__.py", line 880, in emit
    stream.write(fs % msg)
IOError: [Errno 0] Error
Logged from file datastruct.py, line 147
[INFO] Building Analysis because Analysis-00.toc is non existent
1753 INFO: Initializing module dependency graph...
[INFO] Initializing module dependency graph...
1759 INFO: Initializing module graph hooks...
[INFO] Initializing module graph hooks...
1865 INFO: running Analysis Analysis-00.toc
[INFO] running Analysis Analysis-00.toc
1901 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by c:\el\tools\python\python27\python.exe
[INFO] Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by c:\el\tools\python\python27\python.exe
2030 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_60a5df56e60dc5df.manifest
[INFO] Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_60a5df56e60dc5df.manifest
2032 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
[INFO] Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
2035 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
[INFO] Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
2037 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_f47b3af6f659a4cf.manifest
[INFO] Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_f47b3af6f659a4cf.manifest
2165 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30729.9317_none ...
[INFO] Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30729.9317_none ...
2166 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_508dca76bcbcfe81.manifest
[INFO] Found manifest C:\WINDOWS\WinSxS\Manifests\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_508dca76bcbcfe81.manifest
2169 INFO: Searching for file msvcr90.dll
[INFO] Searching for file msvcr90.dll
2170 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_508dca76bcbcfe81\msvcr90.dll
[INFO] Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_508dca76bcbcfe81\msvcr90.dll
2170 INFO: Searching for file msvcp90.dll
[INFO] Searching for file msvcp90.dll
2171 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_508dca76bcbcfe81\msvcp90.dll
[INFO] Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_508dca76bcbcfe81\msvcp90.dll
2171 INFO: Searching for file msvcm90.dll
[INFO] Searching for file msvcm90.dll
2171 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_508dca76bcbcfe81\msvcm90.dll
[INFO] Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_508dca76bcbcfe81\msvcm90.dll
2298 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_60a5df56e60dc5df.manifest
[INFO] Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_60a5df56e60dc5df.manifest
2301 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
[INFO] Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
2303 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
[INFO] Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
2Traceback (most recent call last):
  File "c:\el\tools\python\python27\lib\logging\__init__.py", line 870, in emit
    stream.write(ufs % msg)
IOError: [Errno 0] Error
Logged from file winmanifest.py, line 376
[INFO] Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_f47b3af6f659a4cf.manifest
2324 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9317)
[INFO] Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9317)
2469 INFO: Caching module hooks...
[INFO] Caching module hooks...
2475 INFO: Analyzing C:\repos\Client\MachineSC.py
[INFO] Analyzing C:\repos\Client\MachineSC.py
5667 INFO: Processing pre-find module path hook   distutils
[INFO] Processing pre-find module path hook   distutils
6268 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
[INFO] Processing pre-safe import module hook   urllib3.packages.six.moves
9367 INFO: Processing pre-safe import module hook   _xmlplus
[INFO] Processing pre-safe import module hook   _xmlplus
9995 INFO: Processing pre-safe import module hook   win32com
[INFO] Processing pre-safe import module hook   win32com
11599 INFO: Loading module hooks...
[INFO] Loading module hooks...
11600 INFO: Loading module hook "hook-distutils.py"...
[INFO] Loading module hook "hook-distutils.py"...
11601 INFO: Loading module hook "hook-sysconfig.py"...
[INFO] Loading module hook "hook-sysconfig.py"...
11601 INFO: Loading module hook "hook-appdirs.py"...
[INFO] Loading module hook "hook-appdirs.py"...
11604 INFO: Excluding import 'win32com'
[INFO] Excluding import 'win32com'
11605 INFO:   Removing import of win32com.shell.shell from module appdirs
[INFO]   Removing import of win32com.shell.shell from module appdirs
11621 INFO:   Removing import of win32com.shell from module appdirs
[INFO]   Removing import of win32com.shell from module appdirs
11622 INFO:   Removing import of win32com.shell.shellcon from module appdirs
[INFO]   Removing import of win32com.shell.shellcon from module appdirs
11622 INFO: Loading module hook "hook-xml.py"...
[INFO] Loading module hook "hook-xml.py"...
11763 INFO: Loading module hook "hook-httplib.py"...
[INFO] Loading module hook "hook-httplib.py"...
11765 INFO: Loading module hook "hook-PyQt4.py"...
[INFO] Loading module hook "hook-PyQt4.py"...
11781 INFO: Loading module hook "hook-encodings.py"...
[INFO] Loading module hook "hook-encodings.py"...
13798 INFO: Loading module hook "hook-PyQt4.QtGui.py"...
[INFO] Loading module hook "hook-PyQt4.QtGui.py"...
15551 INFO: Loading module hook "hook-pkg_resources.py"...
[INFO] Loading module hook "hook-pkg_resources.py"...
17607 INFO: Loading module hook "hook-certifi.py"...
[INFO] Loading module hook "hook-certifi.py"...
1Traceback (most recent call last):
  File "c:\el\tools\python\python27\lib\logging\__init__.py", line 870, in emit
    stream.write(ufs % msg)
IOError: [Errno 0] Error
Logged from file imphook.py, line 375
[INFO] Loading module hook "hook-dsdev_utils.py"...
17640 INFO: Loading module hook "hook-pywintypes.py"...
[INFO] Loading module hook "hook-pywintypes.py"...
19435 INFO: Loading module hook "hook-win32com.py"...
[INFO] Loading module hook "hook-win32com.py"...
20432 INFO: Loading module hook "hook-PyQt4.QtCore.py"...
[INFO] Loading module hook "hook-PyQt4.QtCore.py"...
20779 INFO: Loading module hook "hook-pythoncom.py"...
[INFO] Loading module hook "hook-pythoncom.py"...
22380 INFO: Looking for ctypes DLLs
[INFO] Looking for ctypes DLLs
22429 INFO: Analyzing run-time hooks ...
[INFO] Analyzing run-time hooks ...
22434 INFO: Including run-time hook 'pyi_rth_pkgres.py'
[INFO] Including run-time hook 'pyi_rth_pkgres.py'
22461 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
[INFO] Including run-time hook 'pyi_rth_win32comgenpy.py'
22485 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
[INFO] Including run-time hook 'pyi_rth_multiprocessing.py'
22499 INFO: Including run-time hook 'pyi_rth_qt4plugins.py'
[INFO] Including run-time hook 'pyi_rth_qt4plugins.py'
22545 INFO: Looking for dynamic libraries
[INFO] Looking for dynamic libraries
23231 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.21022.8_none_5926f98ceadc42c2.manifest
[INFO] Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.21022.8_none_5926f98ceadc42c2.manifest
23234 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.4148_none_ecff360cfb2594f3.manifest
[INFO] Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.4148_none_ecff360cfb2594f3.manifest
23236 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_ed01d9e4fb230e88.manifest
[INFO] Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_ed01d9e4fb230e88.manifest
23365 INFO: Searching for assembly x86_Microsoft.VC90.MFC_1fc8b3b9a1e18e3b_9.0.30729.6161_none ...
[INFO] Searching for assembly x86_Microsoft.VC90.MFC_1fc8b3b9a1e18e3b_9.0.30729.6161_none ...
23366 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_4bf7e3e2bf9ada4c.manifest
[INFO] Found manifest C:\WINDOWS\WinSxS\Manifests\x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_4bf7e3e2bf9ada4c.manifest
23369 INFO: Searching for file mfc90.dll
[INFO] Searching for file mfc90.dll
23369 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_4bf7e3e2bf9ada4c\mfc90.dll
[INFO] Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_4bf7e3e2bf9ada4c\mfc90.dll
23370 INFO: Searching for file mfc90u.dll
[INFO] Searching for file mfc90u.dll
23370 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_4bf7e3e2bf9ada4c\mfc90u.dll
[INFO] Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_4bf7e3e2bf9ada4c\mfc90u.dll
23370 INFO: Searching for file mfcm90.dll
[INFO] Searching for file mfcm90.dll
23371 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_4bf7e3e2bf9ada4c\mfcm90.dll
[INFO] Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_4bf7e3e2bf9ada4c\mfcm90.dll
23371 INFO: Searching for file mfcm90u.dll
[INFO] Searching for file mfcm90u.dll
23371 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_4bf7e3e2bf9ada4c\mfcm90u.dll
[INFO] Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_4bf7e3e2bf9ada4c\mfcm90u.dll
23498 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.21022.8_none_5926f98ceadc42c2.manifest
[INFO] Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.21022.8_none_5926f98ceadc42c2.manifest
23500 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.4148_none_ecff360cfb2594f3.manifest
[INFO] Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.4148_none_ecff360cfb2594f3.manifest
23503 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_ed01d9e4fb230e88.manifest
[INFO] Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_ed01d9e4fb230e88.manifest
23505 INFO: Adding redirect Microsoft.VC90.MFC version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
[INFO] Adding redirect Microsoft.VC90.MFC version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
24082 INFO: Looking for eggs
[INFO] Looking for eggs
24084 INFO: Using Python library c:\el\tools\python\python27\python27.dll
[INFO] Using Python library c:\el\tools\python\python27\python27.dll
24085 INFO: Found binding redirects:
[BindingRedirect(name=u'Microsoft.VC90.CRT', language=None, arch=u'x86', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 9317), publicKeyToken=u'1fc8b3b9a1e18e3b'), BindingRedirect(name=u'Microsoft.VC90.MFC', language=None, arch=u'x86', oldVersion=(9, 0, 21022,
8), newVersion=(9, 0, 30729, 6161), publicKeyToken=u'1fc8b3b9a1e18e3b')]
[INFO] Found binding redirects:
[BindingRedirect(name=u'Microsoft.VC90.CRT', language=None, arch=u'x86', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 9317), publicKeyToken=u'1fc8b3b9a1e18e3b'), BindingRedirect(name=u'Microsoft.VC90.MFC', language=None, arch=u'x86', oldVersion=(9, 0, 21022,
8), newVersion=(9, 0, 30729, 6161), publicKeyToken=u'1fc8b3b9a1e18e3b')]
24095 INFO: Warnings written to C:\repos\Client\.pyupdater\work\win\warn-win.txt
[INFO] Warnings written to C:\repos\Client\.pyupdater\work\win\warn-win.txt
24149 INFO: Graph cross-reference written to C:\repos\Client\.pyupdater\work\win\xref-win.html
[INFO] Graph cross-reference written to C:\repos\Client\.pyupdater\work\win\xref-win.html
24287 INFO: checking PYZ
[INFO] checking PYZ
24287 INFO: Building PYZ because PYZ-00.toc is non existent
[INFO] Building PYZ because PYZ-00.toc is non existent
24288 INFO: Building PYZ (ZlibArchive) C:\repos\Client\.pyupdater\work\win\PYZ-00.pyz
[INFO] Building PYZ (ZlibArchive) C:\repos\Client\.pyupdater\work\win\PYZ-00.pyz
24917 INFO: Building PYZ (ZlibArchive) C:\repos\Client\.pyupdater\work\win\PYZ-00.pyz completed successfully.
[INFO] Building PYZ (ZlibArchive) C:\repos\Client\.pyupdater\work\win\PYZ-00.pyz completed successfully.
25025 INFO: checking PKG
[INFO] checking PKG
25026 INFO: Building PKG because PKG-00.toc is non existent
[INFO] Building PKG because PKG-00.toc is non existent
25027 INFO: Building PKG (CArchive) PKG-00.pkg
[INFO] Building PKG (CArchive) PKG-00.pkg
25270 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9317)
[INFO] Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9317)
29998 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
[INFO] Building PKG (CArchive) PKG-00.pkg completed successfully.
30026 INFO: Bootloader c:\el\tools\python\python27\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
[INFO] Bootloader c:\el\tools\python\python27\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
30027 INFO: checking EXE
[INFO] checking EXE
30029 INFO: Building EXE because EXE-00.toc is non existent
[INFO] Building EXE because EXE-00.toc is non existent
30030 INFO: Building EXE from EXE-00.toc
[INFO] Building EXE from EXE-00.toc
30030 INFO: Appending archive to EXE C:\repos\Client\pyu-data\new\win.exe
[INFO] Appending archive to EXE C:\repos\Client\pyu-data\new\win.exe
30074 INFO: Building EXE from EXE-00.toc completed successfully.
[INFO] Building EXE from EXE-00.toc completed successfully.
30105 DEBUG: Changing to Directory --> C:\repos\Client\pyu-data\new
30107 DEBUG: Got win .exe
30107 DEBUG: Temp Name: win
30108 DEBUG: Appname: win.exe
30108 DEBUG: Version: 1.0.0
30109 DEBUG: starting archive
30109 DEBUG: Temp file: MachineSoftwareDeployClient.exe
30157 DEBUG: Changing to Directory --> C:\repos\Client\pyu-data\new
30164 DEBUG: Moving back to Directory --> C:\repos\Client\pyu-data\new
30170 DEBUG: Archive output filename: C:\repos\Client\pyu-data\new\MachineSoftwareDeployClient-win-1.0.0.zip
30184 DEBUG: Archive name: C:\repos\Client\pyu-data\new\MachineSoftwareDeployClient-win-1.0.0.zip
30185 DEBUG: Moving back to Directory --> C:\repos\Client
30185 INFO: C:\repos\Client\pyu-data\new\MachineSoftwareDeployClient-win-1.0.0.zip has been placed in your new folder

[INFO] C:\repos\Client\pyu-data\new\MachineSoftwareDeployClient-win-1.0.0.zip has been placed in your new folder

30186 INFO: Build finished in 28.92 seconds.
[INFO] Build finished in 28.92 seconds.
`

**Comment by douglasmccormickjr** [comment]
Have you tried to compile the your app without pyupdater and just within pyinstaller instead?  Could you post on you success/test with that?  I'm curious if it'll hit any issues with pyinstaller since that's the process that's really powering pyupdater and attaching the updating mechanism.

Also, does your app pull libraries or files in a dynamic manner (not easily pathable when it's read)-- I've seen some apps that "compile" be will have issues with pulling in dynamic imports that are not properly found/declared...Is there a way you can post some of the code?

Thanks,
-Doug Jr.

**Comment by Jazzman82** [comment]
Yes it works just fine with just pyinstaller. And it also seems to work with pyupdater up to some point after the generation of the .exe. 
The app is using some packages but none dynamically pulled in. I don't think this is the source of the problem as pyinstaller alone is just running fine.

Things I noticed:
- the -n parameter for pyinstaller is ignored
- when using pyupdater with -k the generated .exe is stored in **pyu-data\new **, named **win.exe**

For now, we get away with the following workaround: 
1) using the step-by-step instruction (https://www.pyupdater.org/usage-cli/) including step 7, using **-k**
2) rename/move the generated `pyu-data\new\win.exe` to `pyu-data\new\<app-name>\<app-name>.exe`
3) zip the `pyu-data\new\<app-name>`-directory as `<app-name>.zip`
4) continue with step 8

Not nice, but works at the moment.

**Comment by JMSwag** [comment]
Hey @Jazzman82, can you post the spec file in .pyupdater/spec?

**Comment by Jazzman82** [comment]
Sure, here it is, it is named `win.spec`

```
# -*- mode: python -*-

block_cipher = None


a = Analysis(['C:\\repos\\DeployMachineSoftwareClient\\Startup.py'],
             pathex=['C:\\repos\\DeployMachineSoftwareClient', u'C:\\repos\\DeployMachineSoftwareClient\\.pyupdater\\spec'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[u'c:\\python\\python27\\lib\\site-packages\\pyupdater\\hooks'],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='win',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=False )
```

**Comment by JMSwag** [comment]
@Jazzman82 Looks like a pretty standard pyupdater spec. From the logs, looks like all went well. Would you mind trying with the master branch? Also, could you try with a toy script.

Oh and just for context, the -n parameter is purposely ignored as pyupdater needs a known name for the wrapping of pyinstaller to work correctly. Hence the name attribute of spec files are platform specific.

**Comment by Jazzman82** [comment]
@JMSwag I just updated to the v3.0.1 and unfortunately the behavior is still the same. Even with a dummy-script as you suggested...

**Comment by JMSwag** [comment]
@Jazzman82 I'm still unable to reproduce which makes it hard for me to fix.

**Comment by JMSwag** [comment]
@Jazzman82 Would it be too much for you to create a github repo which I can clone and reproduce to issue?
