### ISSUE TITLE
Bundling files

### ISSUE THREAD

**Issue by JPFrancoia** [Digital-Sapphire/PyUpdater#17]
Hi,

After a few tests, I would like to use pyupdater for "real" projects.

I'm developing a GUI software, and I would like to bundle data files (icons, text files, etc).

Here is my nix64.spec:

``` python
# -*- mode: python -*-

block_cipher = None

added_files = [('images/*', 'images'),
               ('journals/*', 'journals'),
               ('config/data.bin', 'config'),
               ('config/regex.txt', 'config'),
               ('config/stop_words.txt', 'config'),
               ('config/tuto.txt', 'config'),
               ('config/version.txt', 'config'),
               ('config/whatsnew.txt', 'config'),
               ('config/fields/*', 'config/fields')
               ]

imports = ['packaging', 'packaging.version', 'packaging.specifiers', 'packaging.requirements']

excludes = ['pyi_rth_pkgres', 'pyi_rth_qt4plugins', 'pkg_resources', 'lib2to3',
            'runpy', 'xmlrpc', 'doctest', 'tty', 'getopt']

a = Analysis(['/home/djipey/informatique/python/ChemBrows/gui.py'],
             pathex=['/home/djipey/informatique/python/ChemBrows', '/home/djipey/informatique/python/ChemBrows'],
             binaries=None,
             datas=added_files,
             hiddenimports=imports,
             hookspath=['/home/djipey/.local/share/virtualenvs/cb/lib/python3.5/site-packages/pyupdater/hooks'],
             runtime_hooks=[],
             excludes=excludes,
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)

rm_bins = ['libQtWebKit', 'libQtGui', 'libQtXmlPatterns', 'libmysqlclient',
           'libQt3Support', 'libwebp', 'libXss', 'libXft', 'libcrypto', 'libtcl',
           'libtk', 'libX11', 'libgstreamer', 'libgcrypt', 'libQtOpenGL.so',
           'libfbclient', 'libfreetype', 'libgcc_s', 'libsqlite3',
           'libQtDBus', 'libsystemd', 'libgstvideo', 'liborc', 'libharfbuzz', 'libpcre',
           'libmng', 'bncursesw', 'libgstbase', 'libgstaudio', 'liblcms2', 'libQtSvg',
           'liblapack', 'libatlas', 'libgobject', 'libopenjp2', 'libquadmath',
           'libgsttag', 'libmpdec', 'libgstpbutils', 'libxcb-glx', 'libICE', 'libQtXml',
           'libfontconfig', 'libglapi', 'libgraphite2', 'libexpat', 'libXext', 'liblz4']
full_tuples = []
for each_bin in a.binaries:
    for each_rm_bin in rm_bins:
        if each_rm_bin in each_bin[0]:
            full_tuples.append((each_bin[0], None, None))

a.binaries = a.binaries - TOC(full_tuples)

pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='nix64',
          debug=False,
          strip=False,
          upx=True,
          console=True )
```

Pyupdater builds the package with no error. However, it seems the data are not bundled in the package, because when I try to run the program, I get the following error:

```
Traceback (most recent call last):
  File "gui.py", line 2711, in <module>
  File "gui.py", line 130, in __init__
  File "gui.py", line 256, in logConnection
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/home/djipey/informatique/python/ChemBrows/pyu-data/new/config/version.txt'
Failed to execute script gui
```

(It means the program did not find the file config/version.txt).

If it is possible to bundle files with pyupdater, how should I do it ?

**Comment by JPFrancoia** [comment]
After some debugging, I found the root of the problem. Basically, pyupdater only works with the onefile mode of pyinstaller. Now I understand what @JMSwag said here: https://github.com/cloudmatrix/esky/issues/136#issuecomment-244634245

Any chance pyupdater might one day handle the one dir mode of pyinstaller ? The one file mode is slower, and involves modifications of the code.

**Comment by JMSwag** [comment]
@JPFrancoia Hey buddy, sorry for the late response. I've been unplugged for the past few days. I do plan to support onedir mode. You can track the progress at #16

**Comment by JPFrancoia** [comment]
No problem. As soon as the feature is ready, I will heavily test it.

I don't mean to rush you, but do you have any idea about when it could be ready ? (approximately).

I plan to use pyupdater to ship my project (https://github.com/chembrows/ChemBrows) in the future. Until now, I deployed it with Esky, which is now unmaintained, as you know. 200 hundred persons use my software, and I would like my next release to have a durable update process (it will be hard enough to switch from Esky to pyupdater for the next release, I don't want to do that every week).

**Comment by JMSwag** [comment]
I cannot provide a timeframe as my schedule can be hectic at times. I can say that I'll get started on this right away.

**Comment by JPFrancoia** [comment]
No problem, I'll deal with it.

Let me know if you need anything. As I said, I'll be happy to test the feature.

**Comment by JMSwag** [comment]
Sounds like a plan. I appreciate the help!

**Comment by JPFrancoia** [comment]
Closed. See https://github.com/JMSwag/PyUpdater/issues/16
