### ISSUE TITLE
urllib3 compatibility with requests?

### ISSUE THREAD

**Issue by jameswettenhall** [Digital-Sapphire/PyUpdater#170]
Our application uses the popular Python requests package, which used to include a vendored copy of urllib3, but it now lists urllib3 as a dependency.  This is fine except that requests has constraints about which urllib3 version should be used, currently: `urllib3>=1.21.1,<1.25`.

When someone tries to install our application's requirements, if both PyUpdater and requests are installed in the same `pip install -r requirements.txt` step, we see the following error:

`ERROR: requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.1 which is incompatible.`

I'm not sure what the best solution is.

The problem could be avoided by pinning the urllib3 version in PyUpdater's requirements.txt to
 `urllib3 >= 1.24.1, < 1.25`
or
`urllib3 == 1.24.2`

But I would understand if you didn't want to have urllib3's version pinned to something less than the latest version, just for compatibility with requests.

Otherwise, we might consider reverting to PyInstaller, given that we've never found time to harness the true power of PyUpdater in our application - it is currently just acting as a wrapper around PyInstaller, waiting until we have time to implement automatic updates.  

BTW, I'm also known as @wettenhj

**Comment by JMSwag** [comment]
Hey @jameswettenhall! I wouldn't want to take on the tech debt of keeping in sync with requests' requirements. Would specifying requests before pyupdater in the requirements file work for you?

p.s. Thanks for tying that in. I thought someone was pulling a jack move on your unique avatar.

```
# Causes Error
$ pip install pyupdater requests

# No error
$ pip install requests pyupdater
```

**Comment by jameswettenhall** [comment]
Ah of course, thanks! I did have PyUpdater listed after requests originally, but then I must have sorted the requirements in (case-insensitive) alphabetical order.  Moving PyUpdater below requests certainly looks like a good solution for us!

**Comment by JMSwag** [comment]
NP! Cool beans.
