### ISSUE TITLE
Client update_check() stuck at slow connection

### ISSUE THREAD

**Issue by witalij-s** [Digital-Sapphire/PyUpdater#186]
Hi JMSwag,

i realized that the PyUpdater.Client method `update_check()` can return with a big delay when internet connection is bad. This seems to be due to `_get_manifest_from_http()` is downloading really slowly when given a slow download rate. Do you have any workaround for this? Do you think a timeout for `_get_manifest_from_http()` would be an appropriate solution, to abort scanning the manifest?

Best,
Witalij

**Comment by kenneth46k** [comment]
Hi,
I'm looking for support to convert the WXpython demo code into PYQT5 code.
Please help.
Regards
Kenneth

**Comment by JMSwag** [comment]
Hey @witalij-s, I think that would be a good solution.

**Comment by JMSwag** [comment]
@kenneth46k Please do not hijack issues. Also this is a place to report bugs in PyUpdater not general programming support.

**Comment by JMSwag** [comment]
@witalij-s This can now be set from the cli.

```
$ pyupdater settings --http-timeout 10
```

**Comment by witalij-s** [comment]
Thank you for the quick fix. :)

**Comment by JMSwag** [comment]
@witalij-s NP ;)
