### ISSUE TITLE
Split keys.gz and version.gz into platform specific files

### ISSUE THREAD

**Issue by JessicaTegner** [Digital-Sapphire/PyUpdater#188]
Hi.

As the title says, it would be a big enhancement, if the pyupdater produced files like keys.gz and version.gz could be splitted into platform specific files like keys.windows.gz and versions.windows.gz (and for darwin and linux respectively) and by effect, split their contents into their respective files.
The reason for doing this, is so pyupdater will be easyer to be used in a continuous integration system.
If something like this isn't done, when setting up more
 then one platform in a continuous integration system, the versions.gz and keys.gz file will be overridden and fail one or more platforms unintentionally.

**Comment by JMSwag** [comment]
Hey @NicklasMCHD, I would like to get this implemented. Do note that we'd only need to split the version.gz file.

**Comment by JMSwag** [comment]
## Todo: High Level
I'm wondering if adding this an additional flag to the pkg command would provide any benefit? i.e. --split-version. Without the additional flag I cannot think of, at the moment, any harm it would cause to current workflows. Below is a rough of all I think that would need to be changed without adding the flag.

### KeyHandler
- Refactor [_add_sig](https://github.com/JMSwag/PyUpdater/blob/master/pyupdater/core/key_handler/__init__.py#L101)
  - Make a copy of update_data to use within local scope
  - ~~Write a function to parse out platform specific data~~ I don't think this is needed as each platform will have their own config.pyu
- Refactor  [_write_update_data](https://github.com/JMSwag/PyUpdater/blob/master/pyupdater/core/key_handler/__init__.py#L45)
  - Remove saving update data
  - ~~Write both old and new version files~~ Type of version file written will be dependent the --split-version flag
- Refactor [__init__](https://github.com/JMSwag/PyUpdater/blob/master/pyupdater/core/key_handler/__init__.py#L54)
  - ~~Update self.version_file to be platform specific~~
  - ~~Add self.version_file_compat with the original version of self.version_file~~
  - Allow to work with both the consolidated and split version files

### Client
- [__init__](https://github.com/JMSwag/PyUpdater/blob/master/pyupdater/core/key_handler/__init__.py#L51)
  - ~~Update self.version_file to be platform specific~~
  - Allow to work with both the consolidated and split version files

**Comment by JMSwag** [comment]
I'm going to tackle this by adding the flag as to keep the default behavior the same.

**Comment by JMSwag** [comment]
Hey @NicklasMCHD, I don't use CI/CD for my deploys that use PyUpdater. Can you give me a high level of how you envision your workflow for CI/CD w/ PyUpdater. One place that I didn't take into account was writing the package meta data to the config.pyu. I'm assuming you'd have a separate config.pyu for each platform that'd you upload before the compiling and download once compiling is complete for the next run.

**Comment by JMSwag** [comment]
@NicklasMCHD Please check out my issue-188 branch to see if it fits your needs.

**Comment by JMSwag** [comment]
Added in #190

**Comment by JessicaTegner** [comment]
hi @JMSwag 
This is roughly how a workflow could be done (note that I'm using git as an example here).
* Code update in application (the one using PyUpdater)
* commit to GitHub
* On the GitHub repo, I then have setup a bot / whatever you call it, that checks for something like "v1.0.1a123" in the commit.
* Then it executes pyupdater for both windows and mac, like below, at the same time.

#### For windows
* pyupdater build --app-version=version win.spec
* pyupdater pkg -p -s --split-version (or whatever the flag is)
* pyupdater upload -s scp (I'm always using scp, but other could be used)
* git add .
git commit -m "Build version [version] for platform [platformname]"

Note: That all the git commands are not ment to be run by PyUpdater, but by the builder service. The important part here, is that PyUpdater builds it's build in a way, that doesn't touch the same files at the same time (since you would get git merge conflicts).

I'll check the branch during this or next week, and get back to you.

**Comment by JessicaTegner** [comment]
Sitenote: Do note, that I envision, that the workflow would be the same for all platforms.
Essentially (if using a git repo) pull latest commits. build platform specific build, pkg sign and stuff, upload to release server, commit build files to git repo. I envision that's happening on all platforms.
