### ISSUE TITLE
UnicodeEncodeError when upgrading with non-ascii directory names

### ISSUE THREAD

**Issue by joelhoisko** [Digital-Sapphire/PyUpdater#189]
```
Windows 10
Python 2.7
PyUpdater 2.5.1
PyUpdater-s3-Plugin 3.0.6
```

It seems like PyUpdater breaks if the absolute path of the folder where the app gets upgraded/written contain some sort of non-ascii characters.
This is the traceback:
```
05.06.2019 08:51:54 WARNING: stderr:   File "site-packages\pyupdater\client\updates.py", line 600, in extract_restart
05.06.2019 08:51:54 WARNING: stderr:   File "site-packages\pyupdater\client\updates.py", line 741, in _win_overwrite_restart
05.06.2019 08:51:54 WARNING: stderr:   File "site-packages\pyupdater\client\updates.py", line 159, in process
05.06.2019 08:51:54 WARNING: stderr:   File "site-packages\pyupdater\client\updates.py", line 236, in _win_overwrite_restart
05.06.2019 08:51:54 WARNING: stderr:   File "subprocess.py", line 394, in __init__
05.06.2019 08:51:54 WARNING: stderr:   File "subprocess.py", line 644, in _execute_child
05.06.2019 08:51:54 WARNING: stderr: UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 22: ordinal not in range(128)
```
This occurred on Windows where the users name was `Käyttäjä` (User in Finnish) meaning that the home folder was probably also named Käyttäjä. Checking out the source led me to believe that this has something to do with [this line](https://github.com/JMSwag/PyUpdater/blob/master/pyupdater/client/updates.py#L236) and how it uses `os` to handle paths.

I'll try to scrape together an example and this is still somewhat hypothetical as I haven't reconstructed the bug on my own computer so this is just kinda documenting that this thing happened. Could be tested by trying to upgrade a PyUpdater application in directory whose full pathname contains non-ascii characters probably (that's what I'll do now, will update later).

**Comment by joelhoisko** [comment]
Just tested this out on my own system:
```
Ubuntu 18.04
Python 2.7.15rc1
PyUpdater==2.5.1
PyUpdater-s3-Plugin==3.0.6
```
named a folder `ää`, put the packaged app in there and ran it. The update downloaded as usual and then I fired the `AppUpdate`'s `extra_restart()` function, crashing the program and producing this error log:
```
File "site-packages/pyupdater/client/updates.py", line 602, in extract_restart
File "site-packages/pyupdater/client/updates.py", line 685, in _overwrite
File "shutil.py", line 304, in move
File "posixpath.py", line 73, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 32: ordinal not in range(128
```

**EDIT:**
Seems like it's [line 737](https://github.com/JMSwag/PyUpdater/blob/master/pyupdater/client/updates.py#L737) of updates.py that breaks. According to [this StackOverflow answer](https://stackoverflow.com/questions/5523373/python-how-to-move-a-file-with-unicode-filename-to-a-unicode-folder) we could maybe just declare all path strings as unicode?

**Comment by JMSwag** [comment]
Hey @joelhoisko, I think the best path forward would be to use unicode for all path strings. If you are in a hurry to get this in, PRs are welcome. If not I'll take a look at it.

**Comment by joelhoisko** [comment]
Nice, I can have a look at it first.

**Comment by JMSwag** [comment]
@joelhoisko I forgot about py2 EOL. Do note that PyUpdater will be dropping support for py2 come Jan 1st.

**Comment by JMSwag** [comment]
Hey @joelhoisko, try my issue-189 branch and let me know how it goes.

**Comment by joelhoisko** [comment]
Heyah! Haven't had the chance to test this out yet as my tests always broke to the issue #205(took me a while to get my head wrapped around that) but I'll check it out now on my eab1474b3305b94094e3f7598596f5c40e68a418 commit.

**Comment by joelhoisko** [comment]
Seems like this issue is still happening, tried out it on my own `issue-205` branch, tried to update and restart while in a folder named `ä` and got this log message:
```
... pyinstaller probably messes up the line numbers somewhat
[WARNING] stderr:   File "site-packages/pyupdater/client/updates.py", line 733, in extract_restart
[WARNING] stderr:   File "site-packages/pyupdater/client/updates.py", line 784, in _overwrite
[WARNING] stderr:   File "site-packages/dsdev_utils/paths.py", line 52, in remove_any
[WARNING] stderr: UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 32: ordinal not in range(128)
```
Seems like there are still ascii paths mixed together with unicode paths. I'll try to have a look at it now that I can actually run my app.
