### ISSUE TITLE
[WIP] Migration from esky

### ISSUE THREAD

**Issue by JMSwag** [Digital-Sapphire/PyUpdater#19]
- [ ] Docs with migration steps

**Comment by cbenhagen** [comment]
Why has this issue been closed?

**Comment by JMSwag** [comment]
I didn't think anyone would be interested.

**Comment by flutefreak7** [comment]
This is definitely interesting to me. I'm shopping for an Esky replacement now that it's no longer being maintained. I'm not in a huge hurry, but Esky will likely be the last thing keeping me on 3.4

I'm also on the fence between pyInstaller and Pynsist at this point (coming from cx_freeze and py2exe before that) and haven't had time to try either.

**Comment by JMSwag** [comment]
@flutefreak7 Cool. I'll probably need some assistance in getting this done as I've never used Esky.
