### ISSUE TITLE
Pyupdater custom downloader typo

### ISSUE THREAD

**Issue by kscryoice** [Digital-Sapphire/PyUpdater#209]
`pyupdater/client/__init__.py`

[https://github.com/Digital-Sapphire/PyUpdater/blob/bed22398aecdc8492f41b4bec008258d97bcaa44/pyupdater/client/__init__.py#L433](url)

on function `_get_manifest_from_http` on line 433, missing self on downloader

```python
    def _get_manifest_from_http(self):
        log.debug("Downloading online version file")
        version_files = [self.version_file, self.version_file_compat]


        for vf in version_files:
            try:
                if self.downloader:
                    fd = downloader(vf, self.update_urls)
                else:
```
Should be:

```python
    def _get_manifest_from_http(self):
        log.debug("Downloading online version file")
        version_files = [self.version_file, self.version_file_compat]


        for vf in version_files:
            try:
                if self.downloader:
                    # self added
                    fd = self.downloader(vf, self.update_urls)
                else:
```

Impact:
When using custom downloader, it will not execute _get_update_manifest which is also a method to check the versions.gz.
The pyupdater will skip downloading the versions.gz and will return no new updates.

**Comment by 2press** [comment]
Please make the change and create a pull request. @kscryoice
