### ISSUE TITLE
ProxyManager for urllib3

### ISSUE THREAD

**Issue by witalij-s** [Digital-Sapphire/PyUpdater#213]
Hello,

thank you for the great work you did with this library. Is there any workaround or plans to handle urllib3 behind a proxy? Something like the ProxyManager for urllib3 https://stackoverflow.com/questions/31151615/how-to-handle-proxies-in-urllib3 Thanks in advance!

Best,
Witalij

**Comment by JMSwag** [comment]
Hey @witalij-s, you can use a [custom downloader](https://www.pyupdater.org/usage-client-advanced/#use-your-own-file-downloader).
