### ISSUE TITLE
Utilizing multiprocessing process causes infinite cycle. Is there a work around?

### ISSUE THREAD

**Issue by jamesjmartin** [Digital-Sapphire/PyUpdater#214]
Hi, when using multiprocessing I get into an infinite loop as the pyupdater wrapper seems to get called over and over again.  I verified that the very simplified example code below works as expected when using pyinstaller by itself.  Is there a different way that one needs to handle multiprocessing capabilities when using pyupdater?

```
from multiprocessing import Process

def countdown():
    print ("hi!")

if __name__ == '__main__':
    print ("Hello!")
    p = Process(target=countdown)
    p.start()
    p.join()
```

Expected Output:
```
Hello!
hi!
```

Output from pyupdater created build:
```
Hello!
Hello!
Hello!
Hello!
Hello!
Hello!
...
```

**Comment by JMSwag** [comment]
Try with freeze_support from the multiprocessing module.
