### ISSUE TITLE
Create Folder Asset

### ISSUE THREAD

**Issue by Gracecr** [Digital-Sapphire/PyUpdater#215]
Some of my assets are folders. My program expects a certain folder structure. Specifically, I'm using PyQt, and my .ui files are in a folder that I'd like to add as an asset using PyUpdater. Currently, this is making a zip of an empty folder.

Is there a way that I am able to make folder assets? If not, do you have any guidance as to how I could add this capability?

**Comment by dimitriepirghie** [comment]
From my point of view this is a _pyinstaller_ topic.
But I think you can resolve this in the spec file on __Analysis__ object __binaries__ parameter.
This parameter expects a list of tuples of format (_path_of_local_file_,  _file_location_in_binary_).
E.g.
`[
         ( '/myfolder/foo_assets/design1.ui', 'assets/mainassets' ),
         ( '/myfolder/bar_assets/design2.ui', 'assets/secondaryassets' ),
]`

**Comment by JMSwag** [comment]
Resolved by @dimitriepirghie. Thanks
