### ISSUE TITLE
migrate from ed25519 to pynacl

### ISSUE THREAD

**Issue by mortbauer** [Digital-Sapphire/PyUpdater#216]
It seems ed25519 is not really actively maintained anymore, the advertise to switch to pynacl, even provide an example how to do that [migrating-to-pynacl](https://github.com/warner/python-ed25519#migrating-to-pynacl).
Would this be an option, I maybe could create a pull for it if it is an option for you?

**Comment by JMSwag** [comment]
@mortbauer sounds good to me. A PR is welcomed.
