### ISSUE TITLE
Package failed to install on win 7, 10 , Linuxmint 19.02

### ISSUE THREAD

**Issue by MohamedYousof** [Digital-Sapphire/PyUpdater#221]
All attempts to install the package failed on windows 7, 10 and linux mint 19.02
python 3.6 and 3.7
`pip3 install --upgrade PyUpdater
Collecting PyUpdater
  Using cached https://files.pythonhosted.org/packages/32/89/8199a857df41cd894fcb4c3a5343e30f4843e597f6417769946a091b2b5d/PyUpdater-3.1.1-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: urllib3<2.0,>=1.24.1 in /home/mohamed/GoogleOne_env/lib/python3.6/site-packages (from PyUpdater) (1.25.6)
Requirement already satisfied, skipping upgrade: dsdev-utils>=1.0.4 in /usr/local/lib/python3.6/dist-packages (from PyUpdater) (1.0.4)
Requirement already satisfied, skipping upgrade: certifi>=2019.3.9 in /usr/local/lib/python3.6/dist-packages (from PyUpdater) (2019.9.11)
Requirement already satisfied, skipping upgrade: appdirs>=1.4.3 in /home/mohamed/GoogleOne_env/lib/python3.6/site-packages (from PyUpdater) (1.4.3)
Requirement already satisfied, skipping upgrade: six<2.0,>=1.12.0 in /home/mohamed/GoogleOne_env/lib/python3.6/site-packages (from PyUpdater) (1.12.0)
Collecting bsdiff4==1.1.5 (from PyUpdater)
  Using cached https://files.pythonhosted.org/packages/12/a7/e76afa32f205469e87a0454e731bc9d57f04237da4c0e1d0801a912a1940/bsdiff4-1.1.5.tar.gz
Requirement already satisfied, skipping upgrade: stevedore<2.0,>=1.30.1 in /usr/local/lib/python3.6/dist-packages (from PyUpdater) (1.31.0)
Collecting ed25519<2.0,>=1.5 (from PyUpdater)
  Using cached https://files.pythonhosted.org/packages/58/38/72ec85c953b90552fb015f31248256ef19e89a164a40ff8fef680259a608/ed25519-1.5.tar.gz
Requirement already satisfied, skipping upgrade: pyinstaller>=3.0 in /usr/local/lib/python3.6/dist-packages (from PyUpdater) (3.5)
Requirement already satisfied, skipping upgrade: chardet in /usr/lib/python3/dist-packages (from dsdev-utils>=1.0.4->PyUpdater) (3.0.4)
Requirement already satisfied, skipping upgrade: pbr!=2.1.0,>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from stevedore<2.0,>=1.30.1->PyUpdater) (5.4.3)
Requirement already satisfied, skipping upgrade: setuptools in /home/mohamed/GoogleOne_env/lib/python3.6/site-packages (from pyinstaller>=3.0->PyUpdater) (41.2.0)
Requirement already satisfied, skipping upgrade: altgraph in /usr/local/lib/python3.6/dist-packages (from pyinstaller>=3.0->PyUpdater) (0.16.1)
Installing collected packages: bsdiff4, ed25519, PyUpdater
  Running setup.py install for bsdiff4 ... error
    ERROR: Command errored out with exit status 1:
     command: /home/mohamed/GoogleOne_env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-b7ge_gzm/bsdiff4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-b7ge_gzm/bsdiff4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-q3cd4eim/install-record.txt --single-version-externally-managed --compile --install-headers /home/mohamed/GoogleOne_env/include/site/python3.6/bsdiff4
         cwd: /tmp/pip-install-b7ge_gzm/bsdiff4/
    Complete output (20 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/bsdiff4
    copying bsdiff4/cli.py -> build/lib.linux-x86_64-3.6/bsdiff4
    copying bsdiff4/format.py -> build/lib.linux-x86_64-3.6/bsdiff4
    copying bsdiff4/test_all.py -> build/lib.linux-x86_64-3.6/bsdiff4
    copying bsdiff4/__init__.py -> build/lib.linux-x86_64-3.6/bsdiff4
    running build_ext
    building 'bsdiff4.core' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/bsdiff4
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/mohamed/GoogleOne_env/include -I/usr/include/python3.6m -c bsdiff4/core.c -o build/temp.linux-x86_64-3.6/bsdiff4/core.o
    bsdiff4/core.c:8:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/mohamed/GoogleOne_env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-b7ge_gzm/bsdiff4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-b7ge_gzm/bsdiff4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-q3cd4eim/install-record.txt --single-version-externally-managed --compile --install-headers /home/mohamed/GoogleOne_env/include/site/python3.6/bsdiff4 Check the logs for full command output.
`

**Comment by 2press** [comment]
The problem is not with PyUpdater itself but with bsdiff4. Report at https://github.com/ilanschnell/bsdiff4 if you still have problems.

**Comment by MohamedYousof** [comment]
I have already fixed it with downloading and installing visual studio tools (windows 10 sdk) 
the package installed successfully but still didn't find a step by step tutorial to use it properly
