### ISSUE TITLE
[Question] Downgrade mechanism

### ISSUE THREAD

**Issue by dimitriepirghie** [Digital-Sapphire/PyUpdater#222]
I've been using pyupdater for over an year, amazing framework (thanks to all contributors) and more than 20 version released .
But it happens that a buggy version is released due to insuficient testing or unexpected use cases.

What will be effort to implement a _downgrade_ mechanism ? At least to the previous version.

I know for example that in case we update from __v1.0.0__ to __v1.0.1__ pyupdater will reuse the already available arhive of __v1.0.0__ and patch it to next version. I will be nice to keep the previous version archive to use it for offline downgrade. And in online case if the local archive is not available to download the previous version archive.
The event of downgrade should be triggered by the user in case he is not happy with the new version or is buggy.
Suggestion of update after downgrade should be disabled, somehow save locally that user downgraded and he doesn't want to have the newest version. Or maybe have on __versions.gz__ that the newest version is buggy and not provided as stable update.

I can contribute in this case if some starting points are provided.

**Comment by JMSwag** [comment]
Hey @dimitriepirghie, I would lean more towards heavier usage of the beta and alpha channels. I’m trying to keep client side logic as simple as possible. Level of effort would be pretty substantial. Also with release channels implemented ROI is low.
