### ISSUE TITLE
Uploading a directory instead of a zip/tar file

### ISSUE THREAD

**Issue by jasonkang14** [Digital-Sapphire/PyUpdater#233]
Asking this question here because the is the only channel available to talk to the project owner/contributors

Is there a way to change settings to upload the entire directory--which remains in the `new` directory by using the `--keep`. I guess the correct terminology here is the executable that is formed by using the `build` command. 

I would like to build a system in which a user checks the version and downloads the newest version using `PyUpdater` without having to unzip or install. 

Appreciate your help in advance

**Comment by JMSwag** [comment]
@Jasonkang14, once the user has “installed/unzipped then run” the initial version of your app, subsequent updates would be handled automatically by PyUpdater.

**Comment by jasonkang14** [comment]
I will try that. but my project keeps failing when I try to check the version by using `update_check(APP_NAME, APP_VERSION)`. When I create my zip file using the `build` command, it does create a file like `projectname-win-1.0.6.zip` from which I believe the `update_check()` method must check the version by reading the `1.0.6` in the file name. Do I need to implement anything extra in order to check the version successfully?

**Comment by JMSwag** [comment]
@jasonkang14 You would need to upload the built assets to an online repository. e.g. S3

Check out the [Usage | CLI](https://www.pyupdater.org/usage-cli/) section of the docs.

**Comment by jasonkang14** [comment]
@JMSwag is it not compatible with the scp plugin? I was able to upload the zip file to my server but couldn’t check the version. If ‘update_check’ only works with s3 I’ll change my plugin option
