### ISSUE TITLE
keys.gz is marked as a virus in McAfee

### ISSUE THREAD

**Issue by lin00** [Digital-Sapphire/PyUpdater#234]
Followed demo to create a MVP

Executable file is able to retrieve and download new version, but gets deleted by McAfee after updating because it is detecting `keys.gz` as a virus. 

Anyway around this? For reference, this is what I have in the test server:

`keys.gz`, `[The zip file containing new exe]`, `versions.gz`

**Comment by lin00** [comment]
Update: 

Keys are fine now, but it's saying `_decimal.pyd` is a virus.

**Comment by 2press** [comment]
Deinstall McAfee or report this issue to them. This is a false positive.
