### ISSUE TITLE
Support for Python 3.8?

### ISSUE THREAD

**Issue by Official-Husko** [Digital-Sapphire/PyUpdater#235]
Will there be support for Python 3.8 soon? i would like to use your module/package but i cant use it since pywin32 ver.224 is not available for Python 3.8. Do you think you could make your Module compatible with pywin32 225 or 227?

![cmd](https://user-images.githubusercontent.com/27901510/75185078-c6ecf780-5745-11ea-8169-282cefe13b9d.PNG)

**Comment by JMSwag** [comment]
The pywin32 dependency has been removed. You can use master until the next release is pushed to pypi.

**Comment by LukeSavefrogs** [comment]
So i have to use the development version in order to make it work with Python 3.8?

**Comment by JMSwag** [comment]
@LukeSavefrogs Yes
