### ISSUE TITLE
ssl certificate on https://www.pyupdater.org/ is expired

### ISSUE THREAD

**Issue by claudiug** [Digital-Sapphire/PyUpdater#240]
Hello, currently the ssl certificate from https://www.pyupdater.org/ is expired.

**Comment by JMSwag** [comment]
@claudiug Fixed 😉. Thanks for the report!

**Comment by dennisvang** [comment]
Certificate expired on March 27, 2020. Has not been renewed yet. The resulting "Warning: Potential Security Risk Ahead" is not very inviting...

**Comment by JMSwag** [comment]
@dennisvang Apologies, re-uploaded the expired cert. The new cert should have an expiration of July 10, 2020.

I'm seeing a sync issue with my router. A few hosts are not updating their cert store. Working on this now.

**Comment by JMSwag** [comment]
This should be fully resolved. Please comment if otherwise.

**Comment by dennisvang** [comment]
@JMSwag, looks like it's o.k. now. Thanks for the quick response! PyUpdater is great stuff, by the way. :-)
