### ISSUE TITLE
Crash in debug model

### ISSUE THREAD

**Issue by njxz** [Digital-Sapphire/PyUpdater#241]
my env:  pycharm 2019
python 3.7.4
pyupdate  3.1.1

when i try to debug my program,pyupdater raise Exception
![图片](https://user-images.githubusercontent.com/16254670/79435573-6f129480-8002-11ea-9b48-474abeb405fe.png)

**Comment by JMSwag** [comment]
@njxz Does this only happen when debugging? Can you reproduce when using pyinstaller directly?
