### ISSUE TITLE
`max_download_retries` not set when downloading manifest files and key files

### ISSUE THREAD

**Issue by dennisvang** [Digital-Sapphire/PyUpdater#243]
Description:

Perhaps this is by design, but I noticed that the `MAX_DOWNLOAD_RETRIES` setting has no effect when the client tries to download the manifest and key files.

How to replicate:

For exampe, attempt to download from a non-existent server.

Cause:

The `max_download_retries` argument is not set when initializing the `FileDownloader` in  [_get_manifest_from_http()](https://github.com/Digital-Sapphire/PyUpdater/blob/master/pyupdater/client/__init__.py#L438) and in
[_get_key_data()](https://github.com/Digital-Sapphire/PyUpdater/blob/master/pyupdater/client/__init__.py#L471).

Was this left out on purpose?

**Comment by JMSwag** [comment]
@dennisvang Nice catch. That was missed.
