### ISSUE TITLE
Create release 3.1.2

### ISSUE THREAD

**Issue by segfault16** [Digital-Sapphire/PyUpdater#244]
Hi,

can you please create a current release?
On 3.1.1 there is a bug that is fixed in master

**Comment by segfault16** [comment]
@JMSwag any chance of looking into this?

**Comment by JMSwag** [comment]
@segfault16 Hey, I'll be cutting the next release within the next couple of months. It'll be a major release. For now please install using git.

**Comment by segfault16** [comment]
@JMSwag Major in terms of breaking API changes?

**Comment by JMSwag** [comment]
@segfault16 Mostly dropping of py2.
