### ISSUE TITLE
Authorization header content is logged

### ISSUE THREAD

**Issue by dennisvang** [Digital-Sapphire/PyUpdater#245]
### Observed behavior

While looking through the PyUpdater debug logs, I noticed that the content of the `'Authorization'` header is logged. That means password-equivalent information may be (accidentally) logged to file.

### Steps to reproduce

Initialize a PyUpdater project, set log level `DEBUG`, then:

`client = Client(ClientConfig(), headers=dict(basic_auth='user:pass'), refresh=True)`

This will log the following header:

`{'authorization': u'Basic dXNlcjpwYXNz'}`

### Cause

https://github.com/Digital-Sapphire/PyUpdater/blob/master/pyupdater/client/downloader.py#L167

### Expected behavior

I would expect sensitive information not to be logged, because users may write their logs to file.

Perhaps the Authorization header could be cleaned, e.g. leave the authentication type (e.g. `'Basic'` or `'Bearer'`) in place, but either remove the actual credentials or truncate them.

**Comment by dennisvang** [comment]
A quick and dirty fix could look like this:

`log.debug(
        {key: value.split(' ', 1)[0] 
         if value and key.lower() == 'authorization' else value 
         for key, value in _http.headers.items()})`

**Comment by JessicaTegner** [comment]
I would say, to leave the "authentication type" in, but remove sensitive information. There's no purpose for it to be logged
