### ISSUE TITLE
"Failed to decompress gzip file" when response has "Content-Encoding: gzip" header

### ISSUE THREAD

**Issue by dennisvang** [Digital-Sapphire/PyUpdater#246]
### Observed behavior

`Client.refresh()` fails with a `"Failed to decompress gzip file"` message (debug), for `versions.gz` and `keys.gz` files that are served either directly from _Amazon S3_ or from a _Django_ app (as static file).

### Cause

The cause appears to be the `Content-Encoding: gzip` header, which is set automatically, by these servers, for `*.gz` files.

What happens is that the `urllib3.response.HTTPResponse` will automatically decompress the gzipped file if `Content-Encoding: gzip` is set.  This (default) behavior is described in the [urllib3 documentation](https://urllib3.readthedocs.io/en/latest/reference/urllib3.response.html#urllib3.response.HTTPResponse):

> **decode_content** – If True, will attempt to decode the body based on the ‘content-encoding’ header.

As a result, the `FileDownloader.file_binary_data` attribute will already contain decompressed data when the calls to `_gzip_decompress(data)` are made, so these will raise an `IOError` ([Client._get_manifest_from_http()](https://github.com/Digital-Sapphire/PyUpdater/blob/master/pyupdater/client/__init__.py#L447) and [Client._get_key_data()](https://github.com/Digital-Sapphire/PyUpdater/blob/master/pyupdater/client/__init__.py#L480))
 
### Steps to reproduce

Set up a project and serve the `keys.gz` and/or `versions.gz` files with the `Content-Encoding: gzip` response header. Then call `Client.refresh()`.

### Expected behavior

The client should not fail when a `Content-Encoding` header is set.

### Possible solutions

I guess there are several options. 

The quick fix would be to ignore the `Content-Encoding` header. This can be achieved by passing `decode_content=False` to the `urllib3.response.HTTPResponse`, via [FileDownloader.http_pool.urlopen()](https://github.com/Digital-Sapphire/PyUpdater/blob/master/pyupdater/client/downloader.py#L376):

```python
...
data = self.http_pool.urlopen(
    "GET", file_url, preload_content=False, 
    retries=max_download_retries, decode_content=False)
...
```

Alternatively, we could try to take advantage of the automatic decoding offered by `urllib3`.

**Comment by JMSwag** [comment]
Addressed in #279
