### ISSUE TITLE
[Question] bsdiff4 version (requirements.txt)

### ISSUE THREAD

**Issue by topic2k** [Digital-Sapphire/PyUpdater#247]
In https://github.com/Digital-Sapphire/PyUpdater/blob/ff2aeba62679000b6d8a87a64b06c5944a749d16/requirements.txt#L2
bsdiff4 is pinned to version 1.1.5 but 1.1.9 is available. I guess it was pinned to 1.1.5 because that was the last version supporting Python 2? Or is there another reason? In my venv i have updated bsdiff4 and pyupdater is still doing it's job.

**Comment by JMSwag** [comment]
This needs to be updated

**Comment by shauneccles** [comment]
Bump, bsdiff4 is up to 1.2 now and should be suitable to update the requirements.txt

**Comment by JMSwag** [comment]
Addressed in #278
