### ISSUE TITLE
I have two suggestions for mac platform

### ISSUE THREAD

**Issue by songjt1993** [Digital-Sapphire/PyUpdater#249]
### Problem
On Mac, when execute function "_overwrite()" and "_restart()"， the efficiency is low. I even thought the program was crashed.

### Suggestions
Maybe you can use command line instead of "shutil.move()" and "os.execl()". Details：
```
# pyupdater/client/updates.py : 815

# shutil.move(app_update, self._current_app_dir)
os.system('cp -rf {} {} && rm -rf {}'.format(app_update, self._current_app_dir, app_update))
```
```
# pyupdater/client/updates.py : 251

def _restart(self):
        # os.execl(self.current_app, self.name, *sys.argv[1:])
        os.system('killall {} && open {}'.format(self.name, <path to file.app>))
```

**Comment by JMSwag** [comment]
@songjt1993 Got any benchmarks?

**Comment by JessicaTegner** [comment]
I think the second suggestion here, the restart function, would also fix #207

**Comment by JessicaTegner** [comment]
What would we do, in case of either of the events failing?
If you set a flag to use system commands, and that for some reason fails, what should be done about it?
Should we raise an exception, or just try the way we have currently (but logging the failure).

**Comment by JMSwag** [comment]
I'm thinking something like [this](https://gist.github.com/JMSwag/a7e985a2f45e0b79e73c364326d4baaa). Each restart subroutine would raise its own exception.
