### ISSUE TITLE
macOS. Issues with releases built with --archive-format=zip

### ISSUE THREAD

**Issue by anatolyzenkov** [Digital-Sapphire/PyUpdater#250]
macOS, Plugin: SCP
command example:
`$ pyupdater build --app-version=2.0.1 --archive-format=zip -wyD mac.spec`
tar.gz-release successfully updates to the next tar.gz-release
zip-relase doesn't "see" next zip-release
zip-relase doesn't "see" next tar.gz-release
tar.gz-release crashes when trying to update to the next zip-release

**Comment by anatolyzenkov** [comment]
I found that the content of the app packages is different between zip and tar.gz.
There are some aliases to directories in Resources in tar.gz-releases.
In zip-releases these are empty directories instead of aliases.
Zip-release can't find local certificate file while trying to make update_check.
<img width="830" alt="Screenshot 2020-07-21 at 00 02 01" src="https://user-images.githubusercontent.com/66535/87991845-35609680-cae7-11ea-8870-afef82b53d66.png">
<img width="828" alt="Screenshot 2020-07-21 at 00 02 15" src="https://user-images.githubusercontent.com/66535/87991862-385b8700-cae7-11ea-8152-2a71e90a5a32.png">

**Comment by anatolyzenkov** [comment]
It seams that the problem is with shutil.make_archive. It changes symlinks to empty folders when making zip file. (macOS, Python 3.8.1)

**Comment by anatolyzenkov** [comment]
Found open ticket https://bugs.python.org/issue37601

**Comment by JMSwag** [comment]
Thanks for the report & great find!

Looks like we'll need to do it the long way :)
