### ISSUE TITLE
Update documentation pertaining to CI/CD support

### ISSUE THREAD

**Issue by JessicaTegner** [Digital-Sapphire/PyUpdater#252]
Right now, the only documentation about the CI/CD support are as follows.

`# For CI/CD
$ pyupdater pkg --sign --slit-version
`

I suggest first of all fixing the typo in the command itself, and as an addition actually explain what the extra argument does (ie what the CI/CD support does).

thoughts?

**Comment by JMSwag** [comment]
@NicklasTegner SGTM

**Comment by JMSwag** [comment]
Not sure when this was resolved but it's on main.
