### ISSUE TITLE
Pywin32 version 224 not available on python 3.8 and above

### ISSUE THREAD

**Issue by JessicaTegner** [Digital-Sapphire/PyUpdater#256]
Right now when installing PyUpdater on Python 3.8, windows 10, The following Error pops up.

``
$ poetry add pyupdater
Using version ^3.1.1 for pyupdater

Updating dependencies
Resolving dependencies...

Writing lock file

Package operations: 12 installs, 0 updates, 0 removals

  - Installing chardet (3.0.4)
  - Installing pbr (5.4.5)
  - Installing six (1.15.0)
  - Installing appdirs (1.4.4)
  - Installing bsdiff4 (1.1.5)
  - Installing certifi (2020.6.20)
  - Installing dsdev-utils (1.0.4)
  - Installing ed25519 (1.5)
  - Installing pywin32 (224)

[EnvCommandError]
Command ['C:\\Users\\nickl\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\pyu-test-wmKu1hWO-py3.8\\Scripts\\pip.exe', 'install', '--no-deps', 'pywin32==224'] errored with t
he following return code 1, and output:
Collecting pywin32==224
  ERROR: Could not find a version that satisfies the requirement pywin32==224 (from versions: 225, 226, 227, 228)
ERROR: No matching distribution found for pywin32==224

``

This is due to pywin32, version 224 not having wheels for python 3.8 and above.

This should be a simple fix, bumping pywin32 to a higher version

**Comment by ventorvar** [comment]
Looks like pywin32 was removed in 8387d8e which hasn't been published yet. In the mean time, I've installed the git master version

```
poetry add -E all git+https://github.com/Digital-Sapphire/PyUpdater.git
```

**Comment by JessicaTegner** [comment]
But in that case.
If pywin32 isn't installed, PyUpdater won't be able to update the application if it requires admin privileges

**Comment by CMengich** [comment]
Experiencing the same issue, using Python 3.8 and trying to install PyUpdater. 
Using: pip install PyUpdater

Collecting PyUpdater
  Using cached PyUpdater-3.1.1-py2.py3-none-any.whl (76 kB)
Requirement already satisfied: six<2.0,>=1.12.0 in c:\users\crmen\anaconda3\envs\medical\lib\site-packages (from PyUpdater) (1.15.0)
Processing c:\users\crmen\appdata\local\pip\cache\wheels\6c\49\89\3b05bf30db44014f19147ad96670418565061ae63aa25b3ca1\ed25519-1.5-cp38-cp38-win_amd64.whl
Requirement already satisfied: certifi>=2019.3.9 in c:\users\crmen\anaconda3\envs\medical\lib\site-packages (from PyUpdater) (2020.6.20)
ERROR: Could not find a version that satisfies the requirement pywin32==224; platform_system == "Windows" (from PyUpdater) (from versions: 225, 226, 227, 228)
ERROR: No matching distribution found for pywin32==224; platform_system == "Windows" (from PyUpdater)

pywin32==224 seems to only have installations up to python 3.7.

Any solution to this?

**Comment by JessicaTegner** [comment]
@CMengich  a temporary solution is to install pywin32 manually (you will get something like version 228) and then do pip install pyupdater

**Comment by CMengich** [comment]
@NicklasTegner 
When I try that, this follows:

(Medical) C:\Users\crmen>pip install pywin32
Collecting pywin32
  Using cached pywin32-228-cp38-cp38-win_amd64.whl (9.1 MB)
Installing collected packages: pywin32
Successfully installed pywin32-228

(Medical) C:\Users\crmen>pip install PyUpdater
Collecting PyUpdater
  Using cached PyUpdater-3.1.1-py2.py3-none-any.whl (76 kB)
Processing c:\users\crmen\appdata\local\pip\cache\wheels\e8\bc\86\8562280111e3d904ee307330a9fc27fe0a9298cc0f52baaf81\bsdiff4-1.1.5-cp38-cp38-win_amd64.whl
Collecting appdirs>=1.4.3
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: six<2.0,>=1.12.0 in c:\users\crmen\anaconda3\envs\medical\lib\site-packages (from PyUpdater) (1.15.0)
Collecting stevedore<2.0,>=1.30.1
  Using cached stevedore-1.32.0-py2.py3-none-any.whl (43 kB)
Processing c:\users\crmen\appdata\local\pip\cache\wheels\f1\a9\af\614fe988e920588151f9246474f1d23278643ccf7f6c595355\dsdev_utils-1.0.4-py2.py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement pywin32==224; platform_system == "Windows" (from PyUpdater) (from versions: 225, 226, 227, 228)
ERROR: No matching distribution found for pywin32==224; platform_system == "Windows" (from PyUpdater)

Comes back to the same issue....

**Comment by JessicaTegner** [comment]
hmm @CMengich  could you maybe try installing it from the git repository?

**Comment by CMengich** [comment]
@NicklasTegner 
That seems to have worked. Thanks!

I'm relatively new to using github, the version installed is:
PyUpdater 3.1.1+42.g186b3b0
Out of curiosity, what does the '+42.g186b3b0' refer to?

**Comment by JessicaTegner** [comment]
@CMengich 
"+42.g186b3b0" refers to the current commit. It is the hash of the commit that the repository is currently on.

**Comment by CMengich** [comment]
@NicklasTegner 
Thanks.

**Comment by shauneccles** [comment]
Can we please get a new release pushed to pypi?

The commit that removed the pywin32 dependency was from January 2020.

**Comment by JMSwag** [comment]
Release happening very soon!

**Comment by JMSwag** [comment]
4.0 released

**Comment by dennisvang** [comment]
Pyupdater 4.0 still has critical issues. 

The alternative is to use 3.1.1, but that fails to install on Windows, due to this issue.

Would it be an option to unpin the pywin32 and release that as 3.1.2?

https://github.com/Digital-Sapphire/PyUpdater/blob/27f0874c02c408b1919277f73d1d73f746a5f565/requirements.txt#L7
