### ISSUE TITLE
[ERROR] Missing PYU_AWS_ID

### ISSUE THREAD

**Issue by tommclaughlinjr** [Digital-Sapphire/PyUpdater#257]
I have looked through all the documentation and have no idea where to put the keys. I have also tried the SET command, and using os.environ but continue to get '[ERROR] Missing PYU_AWS_ID'.

I also looked through all the generated files and put the keys into whichever dictionary seemed appropriate for the software to look for them, but I guess I haven't found the right one.

Where do my S3 keys go? I would love some help.

Thanks!

**Comment by JMSwag** [comment]
@tommclaughlinjr Hey, would you mind trying after adding to the user env vars?
