### ISSUE TITLE
Not use swap memory when ram is full?

### ISSUE THREAD

**Issue by bao-O** [Digital-Sapphire/PyUpdater#262]
Currently I'm try to packaging a python project running on Jetson Nano (aarch-linux), but it has only 4GB RAM. This is enough for building executable file but when I perform --process on it, It rapidly fill full ram memory and return `[ERROR]` with no other detail, so I guess that this error come from the lack of memory on this device . The created executable file's size is about 700M. Any work around for this problem? Does PyUpdater not use swap when ram memory is full?

**Comment by JMSwag** [comment]
@DoriHp Sounds like it may be hitting OOM error during patch creation. Are you including assets in your application? If they are not critical during app startup, you could use PyUpdater external assets functionality.

https://www.pyupdater.org/usage-cli-asset/
