### ISSUE TITLE
[ERROR] size does not fit in an int

### ISSUE THREAD

**Issue by hohband** [Digital-Sapphire/PyUpdater#265]
The following error occurred when I try to package the 2nd version and generate the first patch. FYI: The packaged file is quite large, 3,174 MB, I guess it might be the reason

pyupdater pkg --process --sign
[INFO] PyUpdater 3.1.1
[INFO] Processing packages...
[INFO] Patch support enabled
[INFO] Generating package list
[INFO] Starting patch creation
[INFO] Creating patch... Anvsoft BetterVideo-win-stable-2
size does not fit in an int
[ERROR] size does not fit in an int

**Comment by mnauf** [comment]
Same issue. Did you find a fix? @hohband

**Comment by mnauf** [comment]
@hohband  for the time being, I suggest you use `diff` and `patch`. I also have a 3 GB software and following [this](https://www.thegeekstuff.com/2014/12/patch-command-examples/) helped.

**Comment by JMSwag** [comment]
@hohband Are the large file sizes due to shipping large assets inside of the application? I ask as PyUpdater allows external versioned assets.
