### ISSUE TITLE
Pyupdater loops when a new version arrived when using nssm

### ISSUE THREAD

**Issue by AndLvovSky** [Digital-Sapphire/PyUpdater#267]
My program consists of the following steps:
- check for update
- if an update exists, download it, extract and restart the program
- run update checks in a new thread every 30s
- run the main program that prints the word `YAY` every 5s

Here is the code of the update checker:
```
client = Client(ClientConfig, refresh=True)
appUpdate = client.update_check(ClientConfig.APP_NAME,
                                ClientConfig.APP_VERSION,
                                channel='stable')
if appUpdate:
    if hasattr(sys, "frozen"):
        downloaded = appUpdate.download()
        if downloaded:
            status = UpdateStatus.EXTRACTING_UPDATE_AND_RESTARTING
            print('Extracting update and restarting...')
            time.sleep(10)
            appUpdate.extract_restart()
        else:
            status = UpdateStatus.UPDATE_DOWNLOAD_FAILED
    else:
        status = UpdateStatus.UPDATE_AVAILABLE_BUT_APP_NOT_FROZEN
else:
    status = UpdateStatus.NO_AVAILABLE_UPDATES
print(UPDATE_STATUS_STR[status])
```

Furthermore, I'm trying to run the program as a Windows service using [nssm](http://nssm.cc/).

When a new version of a program is uploaded to s3, pyupdater tries to update the program but it never succeeds causing the main program to never start. However, if I don't use **nssm** it works just fine.

[Link to logs](https://pastebin.com/aLKwWSiy)

**Comment by AndLvovSky** [comment]
Apparently, there are 2 issues here:
- Pyupdater files are not creating in `C:\Windows\system32\config\systemprofile\AppData\Local\spd\pyupdaterdemo\update`, if we change update directory to some custom directory files are creating fine
- Pyupdater can not overwrite executable file cause it's being used by wservice.exe

I'm not sure why the first one is happening only if the app is running as a service. One possible solution for the second problem is to remove the service before updating and install it after. But then we need to execute nssm commands with admin access through Python code. Overall it's quite unreliable.

So it's clear that there are a couple of problems when using Pyupdater within a Windows service.

**Comment by JMSwag** [comment]
Hi @AndLvovSky,

From the sound of it, looks to be a permission issue. PyUpdater doesn't have inbuilt support for elevating permissions.
