### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by JoeBarouneD** [Digital-Sapphire/PyUpdater#269]
Hello i'm on Win10, when i try to install Pyupdater by pip, i get an error saying as there is no wheels package and i don't have Visual Studio, it cannot continue.

`building 'ed25519._ed25519' extension
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/`

**Comment by gasd238** [comment]
![image](https://user-images.githubusercontent.com/41102800/103744095-84bc6400-5040-11eb-8b78-7182eee00304.png)
in my case download visual studio community version and download c++ build tools then it will work
you must download msvc you can see it on right side of picture

**Comment by JoeBarouneD** [comment]
So the solution is to download the full VS with build tools 4.7GB package ?

IMO there must be another way ..

**Comment by jgwinner** [comment]
You don't have to install the entire VS, just the build tools - which is the compiler, linker, etc.

Historically, C++ compilers cost hundreds of dollars on the Windows platform, so c/c++ wasn't built in by default (there's that pesky anti-monopoly chants in teh background).

That's changed recently, but you still have to download it separately.

Once you do that, make sure you run the .bat file to setup your paths (I don't recommend setting them manually, as they DO change based on versions).

`C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat -arch=amd64`

Note the `-arch=amd64` **without this, the default is 32 bit code, which isn't what Python needs**.

**Comment by JMSwag** [comment]
I'll look into building wheels.
