### ISSUE TITLE
Comparison

### ISSUE THREAD

**Issue by mnauf** [Digital-Sapphire/PyUpdater#273]
Hey, you are doing great work. Just want to share an observation. 

1- When I create binaries of my software (3GB) using pyupdater, it takes more than half an hour, however when I do so with pyinstaller, it does within 10 minutes. I wonder why is that when pyupdater itself uses pyinstaller.
2- The [patch file sizes are a lot bigger](https://github.com/Digital-Sapphire/PyUpdater/issues/121) with pyupdater. I wrote a simple hello world program and created a patch for a new version with just a few characters change and it made a patch size of 10 MB, when the original binaries size was 13 MB. Doing the same manually using [`diff`](https://www.thegeekstuff.com/2014/12/patch-command-examples/) made it a lot efficient. I got the patch under 200 kB.
3- Pyupdater couldn't create a patch for my 3GB software. It said [size doesn't find in an int](https://github.com/Digital-Sapphire/PyUpdater/issues/265). Doing the same manually with [`diff`](https://www.thegeekstuff.com/2014/12/patch-command-examples/) worked.
4- I find it odd that pyudater when send its first patch for version 2 to its users, software downloads the entire binaries for version 2. Why is that? Using `diff` and `patch`, users don't need to download binaries for any version even this is only for once.
5- I think pyupdater does unnecessary zipping and unzipping of files. We don't need to zip files to create a patch. Pyinstaller doesn't give us a zip file and you can use `diff` on unzipped files just as fine.

Note: To apply the patch, you can use [`patch`](https://www.thegeekstuff.com/2014/12/patch-command-examples/), which is another ubuntu builtin CLI tool that comes along with `diff`

**Comment by JMSwag** [comment]
1. PyUpdater does diffing and PyInstaller does not.
2. Nice!
3. Probably that diff is written in another language.
4. During install if you copy v1 to the update folder, PyUpdater will have a source to patch from.
5. This made it easier to implement as there was only 1 thing to diff instead of having more logic for pyinstaller 1 file vs folder mode.

Thanks for the feedback!
