### ISSUE TITLE
Any platform/any channel

### ISSUE THREAD

**Issue by Fizzadar** [Digital-Sapphire/PyUpdater#274]
Firstly a big thank you for making pyupdater - it has been incredibly useful for my app (kanmail.io).

I was wondering if there is interest in allowing users to specify the platform and use any channel name. I see that the platforms are hardcoded from dsdev-util and the channel names as well. I think making it possible to use any value for both would be incredibly powerful (and solve issues like #268).

Happy to look at PR-ing this change if there's interest?

**Comment by JMSwag** [comment]
@Fizzadar I'll add support for Mac arm in dsdev-utils. Not sure that adding a cli arg would be helpful as you need to build on each platform.

**Comment by JMSwag** [comment]
Mac arm support has been added to dsdev-utils

**Comment by Fizzadar** [comment]
My thinking here was more on the Linux side, where packaging by distribution can be really useful (portable Gnome apps are a nightmare to get working). Thanks for adding the M1 support!

**Comment by JMSwag** [comment]
@Fizzadar Oh I see. I'd be interested in this. NP!
