### ISSUE TITLE
Maintaining PyUpdater

### ISSUE THREAD

**Issue by JessicaTegner** [Digital-Sapphire/PyUpdater#275]
Hello @JMSwag and others  

### For the original author:
I would like to hear, if you're interested to continue development of PyUpdater, and if not, if you're interested in handing over maintainment and further development?

### TO others:
Depending on what @JMSwag answeres, I would like to take over development and maintainment of PyUpdater, as I firmly believe that it has become a central tool in the Python Application Ecosystem.

I hope that my history on this project can speak for itself, that I would be able to handle the development of this project, because I would really don't want to see it die.

I hope a solution / answer can be found.

**Comment by JessicaTegner** [comment]
@JMSwag  there we go :)

**Comment by JMSwag** [comment]
Hey @NicklasTegner, I'm still interested in the project. As it stands currently, the project fulfills all of my needs so I don't have a plan for additional features. I am open to all suggestions and PRs.
