### ISSUE TITLE
Make `latest` attribute public

### ISSUE THREAD

**Issue by JPFrancoia** [Digital-Sapphire/PyUpdater#28]
Hi, I wonder if it is possible to make the `latest` attribute from the class `Client` public.

I would change https://github.com/JMSwag/PyUpdater/blob/master/pyupdater/client/__init__.py#L244 to something like that:

``` python
self.latest = get_highest_version(name, self.platform, channel, self.easy_data)
```

With the idea to later do:

``` python
self.app = client.update_check(client.app_name, version)
log("Updating to version {}".format(client.latest))
```

Basically, I would simply like to log the version that my program is installing, so I can debug more effectively if one of my users encounters a problem.

But maybe I am missing an attribute in your API. If not, I could easily make a PR, if you agree.

**Comment by JMSwag** [comment]
Hey @JPFrancoia, it's exposed [here](https://github.com/JMSwag/PyUpdater/blob/master/pyupdater/client/updates.py#L228), in the [update object](https://github.com/JMSwag/PyUpdater/blob/master/pyupdater/client/updates.py#193) returned by update_check. The client can also update external assets with another call to update_check which is why latest is a local var in the client class.

``` python
# This should work for you
self.app = client.update_check(client.app_name, version)
log("Updating to version {}".format(self.app.latest))
```

Please keep the usibility suggestions coming 👍

**Comment by JPFrancoia** [comment]
Thanks, I missed it in the code !
Just one question though. When I print `self.app.latest` I get something like `0.9.9.2.0`. But the latest version is only labelled `0.9.9`. Could you tell me what the other numbers are ?

**Comment by JMSwag** [comment]
NP. See below for details on the other numbers. What do you think about adding a version attribute to the update object? I'm working on adding an attribute that will return a user friendly string like "1.2.3" or "1.2.3 Beta 1" if it's a prerelease.

Major.Minor.Patch.Channel.Release

Channel: 2=stable, 1=beta, 0=alpha

**Comment by JMSwag** [comment]
@JPFrancoia The next release will expose .version which will have a pretty string

**Comment by JMSwag** [comment]
@JPFrancoia v2.2.0 is up on PyPi which includes the version attribute.

**Comment by JPFrancoia** [comment]
Thanks for the clarification. That's indeed good to have a pretty string in the version number.
