### ISSUE TITLE
False positive `file_requires_admin` on Windows

### ISSUE THREAD

**Issue by dimitriepirghie** [Digital-Sapphire/PyUpdater#286]
On Windows OS, module `pyupdater.client.updates`.
`file_requires_admin(file_path)` function gives false positive, because `open(file_path, "a+")` on any process image file while it's being running always raises `PermissionError` exception.

Propose to use this check instead:
`os.access(file_path, os.W_OK)`

**Comment by JMSwag** [comment]
@dimitriepirghie SGTM

**Comment by pm990320** [comment]
Hi I'm also seeing this issue, would it be possible to release the fix?
