### ISSUE TITLE
PyUpdater unable to install 

### ISSUE THREAD

**Issue by elgizabbasov** [Digital-Sapphire/PyUpdater#289]
Hello I have an issue with downloading PyUpdater. I used pip install PyUpdater on my VSCode terminal however I keep getting this error: 
![image](https://user-images.githubusercontent.com/72108920/120391115-d1eceb00-c2eb-11eb-9ef4-e1c2f8528ada.png)
I am using python 3.9.1 version and I can not find any solutions to this problem. It seems like its having trouble with downloading bsdiff4 lib however I tried pip install bsdiff4 as well and ended up with the same output as in the screenshot. Any help would be appreciated

**Comment by JMSwag** [comment]
From the screenshot, looks to be an issue installing bsdiff.

**Comment by elgizabbasov** [comment]
> From the screenshot, looks to be an issue installing bsdiff.

Do you possibly have any clue as to why this is occurring? What would you recommend I try? I can not find any resources on this problem that's why I am asking. Thank you very much for responding and making such a cool tool :)

**Comment by JMSwag** [comment]
@elgizabbasov I would google search the error received to find a solution.

I closed this ticket as this is not the forum for general software questions. A developer using PyUpdater should be able to debug software installation issues.
