### ISSUE TITLE
app_update.extract_restart and friends need unit tests

### ISSUE THREAD

**Issue by cbenhagen** [Digital-Sapphire/PyUpdater#29]
right now they even have a `pragma: no cover`

**Comment by JMSwag** [comment]
Indeed! PR's are always welcome :smiley:

**Comment by JMSwag** [comment]
@cbenhagen Work on this is taking place on the update-tests branch

**Comment by JMSwag** [comment]
Added in 8745eac2921686d5058ec4aa7ded180c07081221
