### ISSUE TITLE
Upon clicking "update" which restarts my executable, nothing changes and the executable is not updated

### ISSUE THREAD

**Issue by elgizabbasov** [Digital-Sapphire/PyUpdater#296]
Hello everyone, looking out for some help ASAP as this is taking way too long... I am running a Pyqt5 gui with pyupdater and using localhost/8000 as my URL for updates, upon clicking update I get this message on the console (python -m http.server 8000):
```
::1 - - [28/Jun/2021 14:09:37] "GET /versions-win.gz HTTP/1.1" 404 -
1 - - [28/Jun/2021 14:09:48] code 404, message File not found
```

I have not found anything online regarding this issue with versions-win.gz which doesn't seem to exist in any of the examples/projects that use Pyupdater. Can someone please help? Should I ignore this message? I have the patches as stable files and I think the issue with my executable not updating is this that the pyupdater is not able to locate versions-win.gz but where should I have it? How can I create it? Please help

**Comment by JessicaTegner** [comment]
hi @elgizabbasov 
when you run pyupdater pkg --process and pyupdater pkg --sign it creates patches along with keys.gz and versions.gz, which all needs to be uploaded (or in your case, simply moved) to the webserver.
Again in your case, it should be enough to move all the files from "pyu-data/deploy" to the local webservers root.
Hope this helps :)
