### ISSUE TITLE
app_update.extract_restart() is broken on macOS and linux

### ISSUE THREAD

**Issue by cbenhagen** [Digital-Sapphire/PyUpdater#30]
```python
    app_update.extract_restart()
  File "pyupdater/client/updates.py", line 515, in extract_restart
  File "pyupdater/client/updates.py", line 609, in _restart
  File "pyupdater/client/updates.py", line 134, in __init__
  File "posixpath.py", line 70, in join
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by JMSwag** [comment]
Are you using the latest release from PyPI? I'm also dogfooding this lib & don't have any issues on mac or linux. Can you provide a code snippet to reproduce?

**Comment by cbenhagen** [comment]
Sorry for the missing info. It is broken in 2.2.0 and master. I am working on a fix. Will make a PR in some minutes.

**Comment by JMSwag** [comment]
TY sir!

**Comment by cbenhagen** [comment]
@JMSwag was your app really using app_update.extract_restart() on macOS?

**Comment by JMSwag** [comment]
Actually looking back at the code, it's using extract()
