### ISSUE TITLE
Strategy for releasing new builds from CI pipeline

### ISSUE THREAD

**Issue by vvarp** [Digital-Sapphire/PyUpdater#36]
Hi,

I am trying to put PyUpdater to use, and I am kinda struggling to wrap my head around its concepts.

I have an wxPython-based app that needs to be built for two platforms. I managed to get spec files working, I got my runners working (GitLab CI), everything is slowly falling into place.

Now, I just started packaging and signing stuff with PYU, and I realized that `.pyupdater` folder and its `config.pyu` are the central source for all versions metadata, however, they don't really belong in the source code repository.

I need to build my app on two separate systems (one for macOS, one for Windows) and I want to have an alpha release for every commit made on alpha branch (and beta release on commits to beta branch, etc.) - but for this to happen, it seems I'd need to manage `config.pyu` in some other way.

One idea that comes to mind is to upload `config.pyu` after every successful build, and to download it before the next one - but I am not sure if this is the right way to do.

**Comment by JMSwag** [comment]
Hi @vvarp , You'll want to upload the config directory before each build & signing step.

I'd like to develop a better workflow for this.

**Comment by vvarp** [comment]
Is it necessary to upload the whole `.pyupdater` folder, or is `config.pyu` just enough?

**Comment by JMSwag** [comment]
.pyupdater/config.pyu & .pyupdater/spec/

**Comment by cbenhagen** [comment]
I am on the same boat here. This is actually one of the main reason why I did not fully switch to PyUpdater yet.

Let's do some brainstorming. How would this look like in an ideal world? It would be nice to set the private keys and upload plugin credentials via environment variables. This can be done in most CI solutions. The version info could be handled by the upload plugin and stored on the upload destination.  It does actually make sense to have the spec and some other build info in your git repo as it might change from branch to branch.

**Comment by JMSwag** [comment]
@cbenhagen We'd also need to take the config.pyu & break it into smaller pieces. Put the version info in it's own json file or maybe have a version file for each platform.

With the CI release workflow, would you be able to upload a previous release so that PyUpdater can create a patch to the new release?

**Comment by cbenhagen** [comment]
I think it should always try to get the latest version before the currently built one to create a patch. If it can't be found locally it should be downloaded from wherever your configured upload plugin would upload it.

So let's say you do releases in that order:
1.0.0
1.0.1
1.1.0
1.1.1
Then you release 2.0.0
2.0.1
2.0.2

And then release a security update 1.1.2. PyUpdater would then create a patch from 1.1.1 to 1.1.2.

If a user would still have 1.0.0. What would happen is that PyUpdater is downloading 4 patches (1.0.0 -> 1.0.1, 1.0.1 -> 1.1.0, 1.1.0 -> 1.1.1, 1.1.1 -> 1.1.2) and apply them in that order.

**Comment by vvarp** [comment]
BTW - I ended up with syncing the whole `.pyupdater` folder using `awscli`. 

This boils down to running `aws s3 sync s3://BUCKET/.pyupdater .pyupdater` first, then going through the build process, ending with `aws s3 sync .pyupdater s3://BUCKET/.pyupdater`

It might be not ideal, but it does the job for now.

Since I am a newcomer to PyUpdater, I am not really able to participate in brainstorming :) but I think that in an ideal world, handling metadata could/should be done via dedicated webservice. 

Back in the days, when I was using Sparkle to update Mac-only apps, things were usually done via self-hosted PHP-based services that provided ability to upload new builds, edit release notes, view analytics, etc. This worked quite well since non-technical peeps were capable of managing release process, and I wouldn't mind to bring some of that to PyUpdater world.

**Comment by wettenhj** [comment]
So if uploading .pyupdater/config.pyu and .pyupdater/spec/ is encouraged, then what sensitive information could be included?  Just ```keypack['repo']['app_private']``` in config.pyu?  And can we provide that sensitive information with environment variables instead?

For example in the code linked below, where 'app_private' is read from config.pyu, could PyUpdater check for an "APP_PRIVATE" or "PYUPDATER_APP_PRIVATE" environment variable first, before reading it from config.pyu?

https://github.com/JMSwag/PyUpdater/blob/master/pyupdater/key_handler/__init__.py#L125

As mentioned above, many CI platforms support using environment variables to provide sensitive information.  Of course each developer would need to decide whether they trust their CI service to keep that information private and secure.

**Comment by JMSwag** [comment]
@cbenhagen Since PyUpdater needs the previously released version to create the patch, how would your workflow look?

Example, would you upload v1.1.1 to CI before building the security release v1.1.2?

**Comment by JMSwag** [comment]
@vvarp I've been pondering the creation of a metadata server. Someting similar to [Equinox.io](https://equinox.io/), but free & open source. It will more than likely be another repository. PyUpdater Pro?  I'd like to keep this project project on the simple side.

**Comment by JMSwag** [comment]
@wettenhj Not really encouraged but currently the only way to solve this problem. Adding a check for env vars first would be the ideal solution.

I plan on spending quite a bit of time this weekend on the issue backlog.

**Comment by cbenhagen** [comment]
I would love to avoid another service for the version info. This can be pulled from the upload destination. Together with the previous version to create the patch. PyUpdater running on the CI server would download them from the upload destination.

**Comment by JMSwag** [comment]
@cbenhagen Ah! I got it. This shouldn't be too much of a struggle.

**Comment by cbenhagen** [comment]
@JMSwag any news on this?

**Comment by JMSwag** [comment]
Hi Ben. No updates at the moment. I’ve been really busy with my day job. Transitioning to a new position.

**Comment by devAtTheBoat** [comment]
Hi everyone. 

I'm currently working with pyupdater and Jenkins. We aren't using the patch functionality yet, because our apps are lightweight.

Our pipeline look like this.

After developing and testing, the approved pull requests are merged into a dev/build branch, and when the testing is complete, the dev/build branch is merged into the master branch. The local repository has a post-commit hook that calls Jenkins.

In Jenkins, we have two pipelines (for Win and OSX platforms). Each platform has a .pyupdater repository. The pipeline goes like this: 

1. Pull the project from master branch. 
2. Remove the .pyupdater folder inside the master branch 
3. Pull from the designated .pyupdater repository 
4. Generate the app with pyinstaller 
5. Generate the update package with pyupdater
   1. Processed and signed
   1. Using Pyupdater s3 plugin, the package is uploaded to S3
6. Push the changes in .pyupdater to the repo
7. Publish the app to S3 and our local network

We took this approach because creating the updates for different platforms using the same .pyupdater directory made everything more complicated to handle if something went wrong. Also, if two build are being build at the same time, there were some race conditions where the final .pyupdater directory could not have the complete information.

I think there are some things to do better (sometimes Jenkins fails to catch the post-commit hook)

But things seems to be working so far.

**Comment by JMSwag** [comment]
@vfxBoat Thanks for the tip!

**Comment by wettenhj** [comment]
Would anyone be interested in expanding this discussion on strategies for integrating PyUpdater with our applications beyond the topic of continuous integration?  If so, what is everyone's preferred communication mechanism?  Slack?  Google group? Gitter?  A GitHub wiki?  I think a Slack channel could be good for this.

**Comment by JMSwag** [comment]
@wettenhj slack +1

**Comment by JMSwag** [comment]
Hi Everyone,

I've given this a lot of thought & I'd like to revert my stance on this. This is way outside of the original goal I had which was to provide an easy way for apps to stay fresh. I myself do not have the time to invest in this endeavor. If someone would like to jump and take this on, I'd be more than willing to provide guidance on the code base.

**Comment by cbenhagen** [comment]
@JMSwag please consider to reopen this issue. Limiting the build to one developers machine really limits the use of this PyUpdater and makes it harder for apps to stay fresh instead of easy. This does not have to be overengineered. I am sure we can come up with a simple solution.

**Comment by JMSwag** [comment]
Out of scope for project goals
