### ISSUE TITLE
Having issue with version number pattern

### ISSUE THREAD

**Issue by stampedeboss** [Digital-Sapphire/PyUpdater#41]
0.0.1701-19. 

It is reported as an error but I can not determine why.  It follows the documented standard of Major, Minor, Patch, releaseversion.

**Comment by wettenhj** [comment]
I'm not sure where the error is coming from - a traceback might help.

But PyUpdater uses version strings like "0.0.1701.2.19", where the '2' represents a stable release (compared with '1' for beta and '0' for alpha) and '19' is the release number.

If you just use a [Major].[Minor].[Patch] version number, then PyUpdater will automatically add '.2.0' at the end of the version number string in the JSON configuration file: .pyupdater/config.pyu

**Comment by stampedeboss** [comment]
I'd like to get a trace back but this is occurring on pyupdate pkg -p with the following output:
 pyupdater pkg -p
[INFO] Patch support disabled
[INFO] Processing packages...
[INFO] Getting package list
[ERROR] Package version not formatted correctly
[INFO] Adding package meta-data to version manifest
[INFO] Processing packages complete

From what I can tell is appears to be failing in Version, parsing.

**Comment by wettenhj** [comment]
I would guess that VersionError is getting raised either here: https://github.com/JMSwag/dsdev-utils/blob/master/dsdev_utils/helpers.py#L159 or here: https://github.com/JMSwag/dsdev-utils/blob/master/dsdev_utils/helpers.py#L223

Maybe you could create your own build of the dsdev_utils package with extra logging included?

**Comment by stampedeboss** [comment]
Found the issue with my naming.  in the class Versions was incorrect it needs to be modified as follows : 
v_re = re.compile('(?P<major>\d+)\.(?P<minor>\d+)\.?(?P<patch>\d+)?-?(?P<release>[a,b,e,h,l,p,t]+)?**_-?_**(?P<releaseversion>\d+)?')

**Comment by JMSwag** [comment]
@stampedeboss Apologies for being so late on this. You found the spot. Examples include 0.2.0beta1,
1.0.1b1, 2.1.0a2
