### ISSUE TITLE
app version constant

### ISSUE THREAD

**Issue by ccfiel** [Digital-Sapphire/PyUpdater#42]
I have notice in sample code http://www.pyupdater.org/usage-cli/ in section "Step 5 - Integrate PyUpdater"  there is a APP_VERSION.  Would APP_VERSION number be always the same when I used pyupdater build -F --app-version=$VERSION nix64.spec. So if I used $VERSION='1.0.12' APP_VERSION should be also '1.0.12'?

```
# Constants
APP_NAME = 'Acme'
APP_VERSION = '1.0'

```

**Comment by wettenhj** [comment]
Your app needs to know its current version when performing the update check using pyupdater.client.Client.update_check

But you don't need to call it APP\_VERSION.  You could call it myapp.\_\_version\_\_ or os.environ['VERSION'] if you like.

**Comment by ccfiel** [comment]
Hello @wettenhj  I tried to use os.environ['VERSION'] but got this error.
```
Traceback (most recent call last):
  File "app.py", line 14, in <module>
    app_update = client.update_check(APP_NAME, os.environ['VERSION'], channel='stable')
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'VERSION'
```
is this how to use it? or I did something wrong? :)

**Comment by wettenhj** [comment]
It looks like your application can't see your VERSION environment variable.  Maybe dump out the value of os.environ.keys() to check what environment variables your app CAN see.  And then maybe try a different way of setting the VERSION environment variable,

e.g. in bash:

```VERSION=1.0.12 ./my_frozen_app```

**Comment by ccfiel** [comment]
Ok Thanks!
