### ISSUE TITLE
Had everything working until start new release channel

### ISSUE THREAD

**Issue by stampedeboss** [Digital-Sapphire/PyUpdater#44]
I am using the following  Version scheme: 0.0.1701a-## where -## is my pre-release commit identifer, it worked great until I built 0.0.1701b.##.  For example it still is reporting 0.0.1710b-45 (0.0.1710-1-45) as being higher than 0.0.1710a-55 (0.0.1710.0.55).  I understand from the code why it is working that way, but the releaseversion is really worthless since it appears that the release/channel will always be higher for a given patch. For all intents the alpha channel is dead at this point. My stable release will be 1.0.1710 as an example where the pre-release identifiers are no longer needed.

My thinking is that for a given channel, they should only pickup a "higher" version from a higher alternate channel.  For example let's reverse my numbers.  Some work was merged into the beta channel and now sits at 55 while alpha builds have not progressed past 52.  I would not mind someone subscribed to alpha receiving 55. 

I can make it work according to my expectations by removing the release from the tuple used to compare 2 Version Objects.  Another option is changing the order, and placing the releaseversion higher in the hierarchy so that the "channel" is the lowest level but I expect that would cause other issues.

Looking for your insight on the proper direction.

**Comment by JMSwag** [comment]
@stampedeboss When calling update_check, are you specifying a channel?

```
app.update_check('Example app', '0.0.1710a-55', channel='alpha')
```

**Comment by stampedeboss** [comment]
yes, the issue is that when comparing the Version Tuple, the channel occurs before the release version in the tuple.  Using the example, (0, 0, 1710, 2, 55) will always be greater than (0, 0, 1710, 0, 65) so the stable channel will be the only one used. Even if the Alpha channel is the one requested.  So the net result is once a "higher" channel is created it is the only one used.  Alpha < Beta < Stable.

I have forked the code and removed the channel from the comparison methods and it works as expected now since the check ignores the channel and checks the raw version number of (0, 0, 1710, 55) vs (0, 0,1710, 65).  Additionally, the code only considers higher channels in the comparison, so if the requested channel is stable only stable releases are considered, where as Beta looks at both Beta and Stable, Alpha checks all three.

So I guess the change is really against dsdev-utils "helper.py' is where the code change was made.

**Comment by stampedeboss** [comment]
I considered instead of changing the comparison methods of removing the check for higher channels in the current compares but in doing so, you would have to do triple builds as development progressed.

**Comment by JMSwag** [comment]
@stampedeboss Try with my fix-channels branch & reply with your results.

**Comment by stampedeboss** [comment]
No difference:
2017-01-18 05:53:51,154 - pyupdater.client - DEBUG - Version Data:
{u'latest': {u'jetPy': {u'alpha': {u'win': u'0.0.1701.1.53'}, u'daily': {u'win': u'0.0.1701.0.53'}, u'stable': {u'win': u'0.0.1701.2.0'}}}, u'updates': {u'jetPy': {u'0.0.1701.0.48': {u'win': {u'file_hash': u'19bee1db26507f4ae1f95b1ebf959a5d3e3b9aa3f25c7d8c0663669601109331', u'file_size': 27050704, u'filename': u'jetPy-win-0.0.1701d-48.zip'}}, u'0.0.1701.0.49': {u'win': {u'file_hash': u'91595743693ee20c0401a35826fe8173abb513a38ea86d00edf2274818cee479', u'file_size': 27052358, u'filename': u'jetPy-win-0.0.1701d-49.zip'}}, u'0.0.1701.1.53': {u'win': {u'file_hash': u'3a6f8b8a9e9b3fc30ffafa8f152e7fc687c8536bc889bdde0236b07d9f7380ab', u'file_size': 27052358, u'filename': u'jetPy-win-0.0.1701a-53.zip'}}, u'0.0.1701.2.0': {u'win': {u'filename': u'jetPy-win-0.0.1701d-55.zip', u'file_hash': u'f31d9eeb64de08562ffba3b5848d9996caddf6e82fd218ae2e29e28c286dfdda', u'patch_name': u'jetPy-win-2', u'file_size': 27055487, u'patch_hash': u'abe042f67d882b19aceb29db0d6d2be7da3e95be53c447fcce4003219e21ad44', u'patch_size': 39364}}, u'0.0.1701.0.50': {u'win': {u'file_hash': u'9334dca4c85607dec5f8848948a87bef8423370b418646a3f9028ba200823967', u'file_size': 27052358, u'filename': u'jetPy-win-0.0.1701d-50.zip'}}, u'0.0.1701.0.53': {u'win': {u'file_hash': u'f5933533e596fde90269f829f02dd19be52a2a4cb3c4c06c8133573a1da8bb03', u'file_size': 27052357, u'filename': u'jetPy-win-0.0.1701d-53.zip'}}}}}
2017-01-18 05:53:51,154 - dsdev_utils.helpers - DEBUG - Version str: 0.0.1701d-53
2017-01-18 05:53:51,154 - pyupdater.client - DEBUG - Checking for jetPy updates...
2017-01-18 05:53:51,155 - pyupdater.client.updates - DEBUG - Highest version: 0.0.1701.2.0
2017-01-18 05:53:51,155 - dsdev_utils.helpers - DEBUG - Version str: 0.0.1701.2.0
2017-01-18 05:53:51,155 - pyupdater.client - INFO - Current vesion: 0.0.1701.0.53
2017-01-18 05:53:51,155 - pyupdater.client - INFO - Latest version: 0.0.1701.2.0
2017-01-18 05:53:51,157 - pyupdater.client - DEBUG - Update Needed: False
2017-01-18 05:53:51,157 - pyupdater.client - DEBUG - jetPy already updated to the latest version

I thinks it has a 0.0.1710.2.0 version that is higher than 0.0.1710.0.55.  I'm going to fall back to my modifications, which correctly handle the situation.

In the Version Class:

    def __eq__(self, obj):
        mj, mi, p, r, rv = self.version_tuple
        mj2, mi2, p2, r2, rv2 = obj.version_tuple
        return (mj, mi, p, rv) == (mj2, mi2, p2, rv2)

    def __ne__(self, obj):
        mj, mi, p, r, rv = self.version_tuple
        mj2, mi2, p2, r2, rv2 = obj.version_tuple
        return (mj, mi, p, rv) != (mj2, mi2, p2, rv2)

    def __lt__(self, obj):
        mj, mi, p, r, rv = self.version_tuple
        mj2, mi2, p2, r2, rv2 = obj.version_tuple
        return (mj, mi, p, rv) < (mj2, mi2, p2, rv2)

    def __gt__(self, obj):
        mj, mi, p, r, rv = self.version_tuple
        mj2, mi2, p2, r2, rv2 = obj.version_tuple
        return (mj, mi, p, rv) > (mj2, mi2, p2, rv2)

    def __le__(self, obj):
        mj, mi, p, r, rv = self.version_tuple
        mj2, mi2, p2, r2, rv2 = obj.version_tuple
        return (mj, mi, p, rv) <= (mj2, mi2, p2, rv2)

    def __ge__(self, obj):
        mj, mi, p, r, rv = self.version_tuple
        mj2, mi2, p2, r2, rv2 = obj.version_tuple
        return (mj, mi, p, rv) >= (mj2, mi2, p2, rv2)

**Comment by JMSwag** [comment]
I'm not able to reproduce with latest master 878bdccba86f486ced9858bd76205a0dc76fb24e
