### ISSUE TITLE
Signing packages from another OS

### ISSUE THREAD

**Issue by JPFrancoia** [Digital-Sapphire/PyUpdater#47]
Hi,

Let's assume I have these files in the directory ```pyu-data/deploy```

```
ChemBrows-nix64-0.9.9.tar.gz
ChemBrows-nix64-0.9.8.tar.gz
ChemBrows-win-0.9.9.zip
ChemBrows-win-0.9.8.zip
```

If I use the command ```pyupdater pkg --process --sign``` on Windows, versions.gz will be generated with the infos about **all** the versions (Linux AND Windows versions).

When I use the same command on Linux, versions.gz will contain only the infos about Linux versions.

I normally develop on Linux, and I copied the directory ```.pyupdater``` on a virtual machine running Windows.

Is it possible to sign ALL the versions, at once, on Linux ? When I'll start porting my app on OSX, it could become complicated to maintain a single file versions.gz with all the versions from the 3 OS in it.

Thanks !

**Comment by JMSwag** [comment]
Hi Mr @JPFrancoia. You'd drop the --sign flag on each platform except the last. The example below should give you what you're looking for.

```
# Copy .pyupdater folder to Windows vm
# On Windows run
> pyupdater pkg --process

# Copy .pyupdater folder from Windows vm to Mac
# On Mac run
$ pyupdater pkg --process

# Copy .pyupdater folder from Mac to Linux
# On Linux run
$ pyupdater pkg --process --sign

```

**Comment by JPFrancoia** [comment]
Ok thanks, so it's the directory ```.pyupdater``` that I have to copy from OS to OS ? Do I have to repeat the process each time ?

**Comment by JMSwag** [comment]
Yes. The --process command grabs the meta data & writes it to the config.pyu file in the .pyupdater folder. The --sign command takes the the the metadata in the config.pyu, signs it then writes out the keyz.gz & versions.gz to disk.

I use resilio sync on my build machines to remove the need to copy the .pyupdater folder.
