### ISSUE TITLE
Question more than issue

### ISSUE THREAD

**Issue by stampedeboss** [Digital-Sapphire/PyUpdater#49]
What is the proper procedure for cleaning the versions file of old version information.  It seems that the proper automated way would be once the file is no longer stored in the "files" section, the corresponding entry would be deleted after a short period of time.

**Comment by JMSwag** [comment]
@stampedeboss Removing old version information would prevent clients from updating by means of patching. In that case the client would fall back to a full update. You could manually remove unneeded version info from the config.pyu file.

Would you mind me asking why you'd want to remove the old version info?
