### ISSUE TITLE
pyupdater: error: argument command

### ISSUE THREAD

**Issue by xavierzhao** [Digital-Sapphire/PyUpdater#5]
An error occurred when running `pyupdater plugins` after `pip install pyupdater[s3, scp]`

```
D:\sources\python\gc>pyupdater plugins
usage: pyupdater
pyupdater: error: argument command: invalid choice: 'plugins' (choose from 'archive', 'bui
ld', 'clean', 'collect-debug-info', 'init', 'keys', 'make-spec', 'pkg', 'settings', 'uploa
d', 'version')
```

**Comment by JMSwag** [comment]
The docs have been updated for the unreleased version 2.0. I hope to get that up to pypi in the next few weeks.

**Comment by JMSwag** [comment]
@xavierzhao New release is up on pypi! 😄 Please report any issues.
