### ISSUE TITLE
unable to use UAC and version_file

### ISSUE THREAD

**Issue by falsaform** [Digital-Sapphire/PyUpdater#54]
Using the latest PyUpdater (2.3.2) + PyInstaller (3.2.1)
I am unable to use the following in my spec file, 

uac_admin=True,
uac_uiaccess=True,
version_file='version.txt'

they have no effect on the output

**Comment by JMSwag** [comment]
I'll have to investigate. Are you able to get the desired ouput using only pyinstaller?

**Comment by JMSwag** [comment]
@sig-dan Any luck with using only pyinstaller?

**Comment by JMSwag** [comment]
Please reopen if this is still an issue.
