### ISSUE TITLE
[Small issue] APP_VERSION should be a str not float

### ISSUE THREAD

**Issue by peredereyalex** [Digital-Sapphire/PyUpdater#55]
Here I was found a small issue: [User Guide Usage | CLI ](http://www.pyupdater.org/usage-cli/)
Please change `APP_VERSION = 1.0` to `APP_VERSION = '1.0' `

**Comment by JMSwag** [comment]
Good catch!

Fixed in cc981642350d04e9a6afbdde98f9c444e181bae2
