### ISSUE TITLE
Race condition in unittest?

### ISSUE THREAD

**Issue by mayli** [Digital-Sapphire/PyUpdater#60]
Tox will run update_repo_extract and update_repo_restart in parallel, but they will write to the same update_folder. When build the master code on travis-ci.org, it[ fails randomly](https://travis-ci.org/mayli/PyUpdater/builds/201254629).

After I changed "-n auto" to "-n 1", the tests never fail. This might get fixed by changing the APP_NAME to different ones or with commits from [this branch](https://github.com/mayli/PyUpdater/commits/use_custom_update_folder).

**Comment by JMSwag** [comment]
Fixed here c7f8d6680d95ec13141cf8604d45bbb2caa09ed5
