### ISSUE TITLE
Feature: Changelog support

### ISSUE THREAD

**Issue by falsaform** [Digital-Sapphire/PyUpdater#63]
Add the ability to include changelog notes to releases which can be accessed via Client

**Comment by jwaschkau** [comment]
+1

**Comment by JMSwag** [comment]
The changelog can be added to the binary with PyInstaller. See [adding-files-to-the-bundle](https://pythonhosted.org/PyInstaller/spec-files.html?highlight=data#adding-files-to-the-bundle).

**Comment by jwaschkau** [comment]
@JMSwag It would be great to show the changelog before downloading the update, so that the user can decide if he wants to update.

**Comment by JMSwag** [comment]
Hey @jwaschkau, That is a good idea. I didn't think of that initially. If you would like to give it a go, a good place to start would be [here](https://github.com/JMSwag/PyUpdater/blob/master/pyupdater/key_handler/__init__.py#L139-L172). Maybe add a self.changelog_file [here](https://github.com/JMSwag/PyUpdater/blob/master/pyupdater/key_handler/__init__.py#L64-L72). And finish off with CHANGELOG_FILENAME [here](https://github.com/JMSwag/PyUpdater/blob/master/pyupdater/settings.py#L65-L67).

**Comment by jwaschkau** [comment]
Hi @JMSwag I really would like to give it a go. Thanks for the advice where start.

**Comment by JMSwag** [comment]
@jwaschkau NP! Let me know if you need any assistance. I'll work on adding the fetching and parsing stuff to the client.

**Comment by JMSwag** [comment]
Now that I think about it, a less intrusive way of doing this would be to use the asset versioning feature of PyUpdater. Essentially you would keep your change log under version control.

Workflow:

  - Create updates for your app & change log
  - Push updates to server
  - Client will first update the change log on the end users computer
  - Show change log to user
  - Update/Don't Update app based on user decision

More Info:

  - [CLI | Assets](http://www.pyupdater.org/usage-cli-asset/)
  - [Client | Assets](http://www.pyupdater.org/usage-client-asset/)
