### ISSUE TITLE
[ERROR] Unknown Command: _cmd_build

### ISSUE THREAD

**Issue by gianlucaromito** [Digital-Sapphire/PyUpdater#66]
Hi to all.
I'm trying to build my "first" python script with atoupdate feature.
I always get an error:

`(env) PS C:\Users\User\Documents\test35> pyupdater build --app-version=1.0.0 app.py
917 INFO: PyUpdater 2.3.2
[INFO] PyUpdater 2.3.2
924 DEBUG: Config Dir: C:\Users\User\Documents\test35\.pyupdater
924 DEBUG: Config DB: C:\Users\User\Documents\test35\.pyupdater\config.pyu
928 DEBUG: Building from python source file: app.py
928 DEBUG: Source file abs path: C:\Users\User\Documents\test35\app.py
929 DEBUG: Creating directory: C:\Users\User\Documents\test35\.pyupdater\work
949 DEBUG: App Info: {'type': 'script', 'name': 'C:\\Users\\User\\Documents\\test35\\app.py'}
950 DEBUG: Hook directory: c:\users\user\documents\test35\env\lib\site-packages\pyupdater\hooks
951 DEBUG: Make spec cmd: -F --name=win --specpath=C:\Users\User\Documents\test35\.pyupdater\spec --additional-hooks-dir
=c:\users\user\documents\test35\env\lib\site-packages\pyupdater\hooks C:\Users\User\Documents\test35\app.py
**953 ERROR: Unknown Command: _cmd_build
[ERROR] Unknown Command: _cmd_build**`

as you can see I'm working in a venv...
Is there something I'm missing?
Thanks, for support!
Gianluca

**Comment by JMSwag** [comment]
Hey @gianlucaromito, Can you provide a minimal test script so that I can try to reproduce? Have you tried with the master branch?

**Comment by JMSwag** [comment]
@gianlucaromito Please reopen if this is still an issue for you.

**Comment by davidlan2838** [comment]
I meet this issue using the pyupdater-wx-demo proj, with python3.5.4 windows version & pyinstaller develop version also pyupdater is from git

**Comment by jameshilliard** [comment]
I have a potential fix [here](https://github.com/JMSwag/PyUpdater/pull/76).

**Comment by JMSwag** [comment]
Hi @davidlan2838, I've created a new build with @jameshilliard's fix. v2.4.1 should be up on pypi shortly.

**Comment by JMSwag** [comment]
@gianlucaromito try v2.4.1 on pypi.
