### ISSUE TITLE
About version of app

### ISSUE THREAD

**Issue by xavierzhao** [Digital-Sapphire/PyUpdater#7]
I am using `pyupdater build --app-version=1.0.0` to build my app, and package it with 'pyupdater pkg -- process' and 'pyupdater pkg --sign'.

In `pyu-data/deploy/versions.gz`:
'''
{"latest": {"gc": {"stable": {"win": "1.0.0.2.0"}}}, "updates": {"gc": {"1.0.0.2.0": {"win": {"file_size": 5083822, "file_hash": "b7efb833be6288ad26dde3f66c69f13ce8d30faf70574ec1818078981d37019c", "filename": "gc-win-1.0.0.zip"}}}}, "signature": "f0bcbRdtIzVJJ9CkIYM988dVJbBMq5ei2DWSC6RyRiAI+Xje30w6xhfrJH6ZH3e3eWxGn7bqfbeOgdv7KM17Cw"}
'''
Wonder why my version is 1.0.0.2.0????

**Comment by JMSwag** [comment]
Version - Release channel (stable = 2, beta = 1, alpha = 0) - Release version
1.0.0 - 2 - 0

For example:
1.0.0b2 = 1.0.0.1.2
2.1a1 = 2.1.0.0.1

**Comment by xavierzhao** [comment]
@JMSwag Can you tell me which version that I am using in my main script?
`APP_VERSION = '1.0.0'` or `APP_VERSION = '1.0.0.2.0'` ?

part of main script:

```
APP_VERSION = '1.0.0'
client = Client(ClientConfig(), refresh=True)
app_update = client.update_check(APP_NAME, APP_VERSION, channel='stable')
```

My old app(0.9.9) always found new version(1.0.0.2.0) of app and restart until kill it by process name in the Task Manager of my Windows 10.

**Comment by JMSwag** [comment]
@xavierzhao in your script you'll want to use 1.0.0

What you see in the version manifest is what's used internally by PyUpdater.

**Comment by xavierzhao** [comment]
Thanks for your explanation and share your `PyUpdater`, my app is work perfect

**Comment by JMSwag** [comment]
@xavierzhao No problem. I'm glad someone other than myself finds it useful :)
