### ISSUE TITLE
Build and run PyQt4 app on different version of windows

### ISSUE THREAD

**Issue by kr0k0** [Digital-Sapphire/PyUpdater#73]
I have build an app with Python 2.7 and PyQt4 on Windows 10.
I'm using gif and svg images with QtGui.QIcon.

When I start this app on Win10 all works.
But when I try to start this app on Windows 7 the images don't get displayed.

Is this a known bug or a limitation?

**Comment by JMSwag** [comment]
@kr0k0 Try building on windows 7, then running on windows 10.

If that doesn't work please file an issue with [PyInstaller](https://github.com/pyinstaller/pyinstaller), unless it works as expected when not using PyUpdater. In that latter case, please reopen this issue.
