### ISSUE TITLE
Lost arguments when extract_and_execute.

### ISSUE THREAD

**Issue by filonenko-mikhail** [Digital-Sapphire/PyUpdater#74]
I use command line arguments for different application modes.
Also my app has check for updates task. I use extract_and_execute, and app lost its mode, because of empty command line.
Could you please copy sys.argv[1:] to command line of updated app instance?

**Comment by JMSwag** [comment]
@filonenko-mikhail Is it an auto-update sort of thing?

**Comment by filonenko-mikhail** [comment]
I can't say in general about it, but if you provide extract_and_execute api, it is more usable when programmer can setup execution of updated binary.

**Comment by JMSwag** [comment]
@filonenko-mikhail Do you have any suggestions on how you would implement this?

**Comment by filonenko-mikhail** [comment]
```
diff --git a/pyupdater/client/updates.py b/pyupdater/client/updates.py
index d729a97..863f009 100644
--- a/pyupdater/client/updates.py
+++ b/pyupdater/client/updates.py
@@ -163,7 +163,7 @@ class Restarter(object):
             self._restart()

     def _restart(self):
-        os.execl(self.current_app, self.name)
+        os.execl(self.current_app, self.name, *sys.argv[1:])

     def _win_overwrite(self):
         with io.open(self.bat_file, 'w', encoding='utf-8') as bat:
```

**Comment by eullerborges** [comment]
@JMSwag I also have this problem. My app needs parameters on initialization and those parameters are lost on restart/overwrite. @filonenko-mikhail have you found any other solution? Or do you keep an updated version of the library? Thanks!
