### ISSUE TITLE
A small clarification to the creation of upload plugins

### ISSUE THREAD

**Issue by joelhoisko** [Digital-Sapphire/PyUpdater#75]
I had some trouble understanding what 

> Plugins are enabled on installation

on the [doc page](http://www.pyupdater.org/create-upload-plugin/) meant, as I wasn't familiar with using `setup.py` as a maketool. I know that I should have known better (I have only used 'traditional' `Makefile`'s before), but something like

> Finally, run `python setup.py install` to enable your new plugin.

at the end of the example would have helped me at least.

**Comment by JMSwag** [comment]
@joelhoisko Thanks for the suggestion! It's a small change with huge benefits.

If you're up to it, you can edit the file [here](https://github.com/JMSwag/PyUpdater/blob/master/docs/create-upload-plugin.md) then I'll merge your change. If not, no worries. I'll get to it sooner than later.

**Comment by JMSwag** [comment]
Docs updated here e93e337c9b93d1501f4561043c7d189482731c13
