### ISSUE TITLE
Automatically APP_VERSION bundle in the frozen app.

### ISSUE THREAD

**Issue by moscoquera** [Digital-Sapphire/PyUpdater#81]
i have been thinking in this feature: automatically bundle in the frozen app the app_version set on the build command. this would be a great feature for lazy people like me we can easily forget to update the app's version.

i'm trying to figure out the best way to do it:
* **automatically patch and bundle client_config.py:** this is maybe the best approach because all the information is automatically added to the frozen app

* **bundle a cfg file in the app and  write a wrapper to read it:** instead of generating the client_config.py, a simple text pail file could be "secretly" bundled in the frozen app and then loaded at runtime by pyupdater.

* **set APP_VERSION as a environment variable:** instead of bundling something in the app, just set the app_version as a variable. i haven't found a way to set environment variables to pyinstaller yet.

**Comment by JMSwag** [comment]
This can be solved with a build script. A user would add version.txt to their spec file. Then run a script similar to what's below.

```bash
#/usr/bin/env bash

# Usage
# ./build.sh 0.12
version=$1
echo $version > assets/version.txt
pyupdater build --app-verson $version
```
