### ISSUE TITLE
Loop on Starting update batch file

### ISSUE THREAD

**Issue by svaikstude** [Digital-Sapphire/PyUpdater#89]
The issue I have is that in _win_overwrite_restart() subprocess.Popen(args) starts and tries to move files before os._exit(0) happens, which causes permission error and a loop. Old version keeps opening up, finds an update, tries to restart and move it but never manages to do so in time. I have increased ping amount from 5 to 20 to counter this, but maybe there are any other solutions?

**Comment by JMSwag** [comment]
@svaikstude, is this still an issue for you?

**Comment by svaikstude** [comment]
@JMSwag, need some more testing, but it seems to be working fine now.

**Comment by JMSwag** [comment]
@svaikstude Cool. I'll close this for now. Please re-open if it crops up again.
