### ISSUE TITLE
[doc] How are we supposed to expose generated versions ?

### ISSUE THREAD

**Issue by Djiit** [Digital-Sapphire/PyUpdater#95]
Hi, 

I can't find any clues about how I should present the packages to my client.
Does it suppose that a copy of pyu-data/deploy/ is located at `UPDATE_URLS` ?

I might have missed something. Otherwise if you can help, i'll submit a PR enhancing the docs with your answer :ok_hand: .

**Comment by moscoquera** [comment]
you can grab any of the compressed files from **pyu-data/new** if you just build it or from **pyu-data/deploy** if you already signed it

**Comment by Djiit** [comment]
So, given `UPDATE_URLS = ['https://download.example.com/', ]`, I just have to upload pyu-data/* to the folder where `download.example.com` is the configured DNS ?
Or just pyu-data/new/* and pyu-data/deploy/* (without the folder structures) ?

Thanks

**Comment by moscoquera** [comment]
Sorry i misunderstood your question, the process to publish updates to your server is upload the contents of pyu-data/deploy the folder is `download.example.com` is loading. but, you can simplify this process just configuring one of the upload plugins (s3 or scp), the process to upload your updates is on the last 3 steps: http://www.pyupdater.org/usage-cli/#step-10-list-installed-plugins

**Comment by Djiit** [comment]
Thanks, that's a lot clearer ! @JMSwag Would you mind if I submit a PR to amend the docs with that info ?

**Comment by moscoquera** [comment]
i'm not the main developer :laughing::laughing:.
you should ask @JMSwag

**Comment by Djiit** [comment]
thx, edited :).

**Comment by JMSwag** [comment]
@Djiit PR are always welcome!

@moscoquera Thanks for assisting.

**Comment by Djiit** [comment]
I'll do that this weekend. @JMSwag the docs are very frustrating when it gets to getting the update client working. I'll post a second issue cause I can't get it working.

**Comment by JMSwag** [comment]
@Djiit Please reopen if you're still having issues
