### ISSUE TITLE
Does it work with

### ISSUE THREAD

**Issue by zockons12** [Digital-Sapphire/PyUpdater#97]
Does it work with github private, dropbox, Linode, or Amazon Light Sail.

AWS is expensive and I'm not sure what other addon even is.

Lastly, wouldn't it be easy for a client to steal source/vulnerabilities?  Does the client have to redownload application or only certain parts of the job or does he have to download new exe?

Just questions that have puzzled me reading docs.  
Cheers,

**Comment by JMSwag** [comment]
Hi @tysondogerz,

It should work with any service which allows uploading/downloading of binaries. The upload functionally has a plugin in architecture as to enable developers to build an upload plugin for their chosen service.

Are you asking about the source of your application? The client supports full and patch downloads.

**Comment by zockons12** [comment]
@JMSwag  Good to hear,  I have noticed there are plugins for Amazon only and scp.  Do I use scp for Linode or do I have custom create.  Does the Amazon plugin work for Amazon Light? ($5/month).  Heck of a lot cheaper.  So for this to work, I'd have to have a headless server through Linode or Amazon correct with 99% up time?

**Comment by JMSwag** [comment]
@tysondogerz You can use the scp plugin for Linode. Ideally you would want your update server to be available all the time.

I'm not familiar with Amazon light. Would you mind providing a link?

**Comment by zockons12** [comment]
@JMSwag https://amazonlightsail.com/ .  Linode and Amazon lightsail are the best bang for your buck.  What's to stop people from mass distributing your application and then people spamming the server.   

Is there even a way to prevent this?  I see there is mention of keys but is this what that's for or am I misreading? :)

Also could someone not buy application, refund and continue accessing server?

**Comment by JMSwag** [comment]
@Notagrumpycat You can use basic auth. The keys are used to cryptographically sign/verify the update manifest.
