### ISSUE TITLE
Pyupdater [ERROR] Missing PYU_AWS_ID

### ISSUE THREAD

**Issue by wolfamongus2** [Digital-Sapphire/PyUpdater#98]
I’m trying to get pyupdater working at the moment with free amazon storage but I keep getting:
[ERROR] Missing PYU_AWS_ID
 pyupdater upload --service s3 app.py
I don’t see an easy way to do this with CMD
PYIU_AWS_ID = 1231313

I’ve looked through docs and demo but this is not making sense to me.  So you upload your py file, and then have to custom design the job so that it checks for updates through Tkinter (design this as well)?

Do you think you could do a tutorial or make it a bit more explanation?  Thanks.  I have an exe but it is annoying having to re-download it all the time :).  I tried e-mailing you, but your email did not work :(

https://pastebin.com/kASzEN1i

I have read: https://libraries.io/github/JMSwag/PyUpdater .

While this was useful, I am still getting [ERROR] Missing PYU_AWS_ID
It is worth mentioning I also got: client = Client(ClientConfig(), refresh=True) - this is undefined.

**Comment by JMSwag** [comment]
@Hdocers You want to use env vars. This is actually for [PyUpdater-S3-Plugin](https://github.com/JMSwag/PyUpdater-S3-Plugin). I'll need to update the readme on the repo.
