### ISSUE TITLE
Pyupdater updating pyinstaller (optimised?)

### ISSUE THREAD

**Issue by zockons12** [Digital-Sapphire/PyUpdater#99]
Maybe I'm doing something wrong, but I have noticed pyupdater files seem to excessively large and I don't see an optimised method for installing update

An optimum solution would be to freeze everything.  Then when you update, you would simply overwrite the the .py file and separate import file which includes added imports.  I don't think pyupdater does this though.  This would save on the download size of updates and download size in general.

Alternatively, just redownload the exe.  Pyupdater supports this though you could create a simple python script to this also.

**Comment by JMSwag** [comment]
@Notagrumpycat PyUpdater supports patch updates.
